### ISSUE TITLE
Flush post thumbnail after updating Featured image

### ISSUE THREAD

**Issue by listedegarde** [cabrerahector/wordpress-popular-posts#105]
I haven't debugged this yet, but I'm getting the wrong image when using `wpp_get_mostpopular()` with the following HTML.  The same thing happens for {image}

    <div class="popular-thumb">{thumb}</div>

This problem can be solved by adding the following line in [/wordpress-popular-posts.php, line 2469](https://github.com/cabrerahector/wordpress-popular-posts/blob/master/wordpress-popular-posts.php#L2469)

    $remove_cache = $this->__image_resize($p, $file_path, $dim, $crop, $source);

I'm not sure what it's doing, but I came across that "fix" by accident whilst debugging.  I've had the problem twice now, and adding that line fixed it both times.

**Comment by cabrerahector** [comment]
Hi Jonathan!

What exactly do you mean with "wrong image"? Could you please describe the issue in more detail?

**Comment by listedegarde** [comment]
Sorry - I really wasn't too descriptive there!

I was expecting the "featured image" to show up, which it does after my aforementioned change.  Instead an image from the content shows up. 

Some more paculiarites to this problem that could help debugging:

1. The featured image is not "attached" to the page (Add Media > from the dropdown choose "Uploaded to this page")
2. The image that shows up instead **is** in the "uploaded to this page" section.

**Comment by cabrerahector** [comment]
Alright, thanks for the detailed info. Should be easier to figure out what might be going on with this.

I'll try to reproduce this bug on my local setup and post back the results here. If necessary, a proper fix will be pushed as well.

Stay tuned!

**Comment by cabrerahector** [comment]
Also, keep in mind that WPP caches images. If another image was selected as the featured image and you changed it afterwards with another from your media library, WPP won't notice the change and will keep using the first one instead.

**Comment by listedegarde** [comment]
Ah, it could just be that: I'm not the only one using the site, so the featured image might have changed.  I see now that there is a button to clear WPP's thumbnails cache.  I should have tried that first, but didn't know it was there.  Is the cache auto-emptied periodically, and if so, how often?

How about hooking the post save to empty WPP's cache for that post?

**Comment by cabrerahector** [comment]
I was suspecting that might be the case which is why I made that comment earlier :P

> How about hooking the post save to empty WPP's cache for that post?

I think [this solution](http://wordpress.stackexchange.com/questions/76693/which-action-hook-can-i-use-when-a-featured-image-has-been-selected) might be a bit cleaner. That way, WPP will only "listen" when a featured image has been selected - if so, WPP could/should check if an image exists already and delete it before creating a new one.

I'll play around with that and see how it goes.

**Comment by listedegarde** [comment]
Yep, that definitely looks like a better hook.  Keep it up, chief!  :)

**Comment by cabrerahector** [comment]
It's done!

For now, only featured image thumbnails will be regenerated when the user updates it. I plan to extend this functionality to the rest of the options as well (_First image on post_, _First attachment_, _Custom field_) sometime in the future.
