### ISSUE TITLE
How to add class to <a> which has wp-post-image?

### ISSUE THREAD

**Issue by 70599** [cabrerahector/wordpress-popular-posts#109]
Now:
`<a href="#">
	<img src="xxx.jpg">
</a>`
- - -
Wanted:
`<a class="has-post-thumb" href="#">
	<img src="xxx.jpg">
</a>`
or
`<a class="no-post-thumb" href="#">
	<img src="no_thumb.jpg">
</a>`

**Comment by cabrerahector** [comment]
Hi there!

Currently there's no way to add CSS classes to the HTML output without some coding. You'll need to either [build your own custom HTML output](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#how-can-i-use-my-own-html-markup-with-your-plugin "WPP's filter hooks") or use Javascript to add your CSS classes to the widget on page load.
