### ISSUE TITLE
Return data with no HTML

### ISSUE THREAD

**Issue by johnstew** [cabrerahector/wordpress-popular-posts#112]
Hi there,

Was wondering if there was a way to just return the data from the plugin. Reason I am asking is because I am using Twig as my template engine right now and would love just the data and let twig handle my render. Is there any way to do this?

Thanks!

**Comment by rahulnever2far** [comment]
Similar request here #110

**Comment by cabrerahector** [comment]
Hey guys!

Indeed, this is already being discussed in #110. Let's move the conversation over there, alright?

**Comment by cabrerahector** [comment]
Ah, about the Twig thing: I'm not really familiar with it (first time I've heard of it, tbh). If you can't wait until I'm done with [this](https://github.com/cabrerahector/wordpress-popular-posts/issues/110#issuecomment-224006453) then you might want to have a look at [this](philsmart.me/wordpress-popular-posts-plugin-raw-data-array/).
