### ISSUE TITLE
duplicate post display - avoiding post display in sidebar when in post page

### ISSUE THREAD

**Issue by yoscbd** [cabrerahector/wordpress-popular-posts#119]
hi there and thank you again for a great plugin.

i have a small issue \question:

my site display popular post in the sidebar for all pages \posts pages.
i want to know if it is possible to hide \ remove a post from the sidebar if the user is in that post page...

lest say user is visiting a post page www.ggg.vvv/post005
in the sidebar he see the same post as well.

i want to know ifthis is somthing that caan be avoided - 
**when in a post page - do not display that post in the poplular posts sidebar.
thanks!**

**Comment by cabrerahector** [comment]
Hi there!

Sorry for the late reply.

There's no way to hide the current entry from the popular posts list. At least not from within the plugin.

Use either CSS or Javascript to do so:

CSS:
```css
.wpp-list li.current {
    display: none;
}
```

Javascript (jQuery):
```js
jQuery(document).ready(function($){
    $(".wpp-list").children("li.current").hide(); // ... or remove() if you prefer that
});
```

**Comment by yoscbd** [comment]
this dosnt help so much, i didnt find the "current" class for any of the LI element...
is there another way to do that?
or is there something i should do to make the plugin add the "current" class?

**Comment by cabrerahector** [comment]
Hi there!

I was checking the WordPress forum and noticed that you asked this question there as well. I was going to leave a reply linking back to this topic and just now noticed that you left a reply after I closed this issue.

Can you please share your site's URL so I can take a look at your sidebar?

**Comment by maustyle** [comment]
There is no such a list item for current posts.

Is there any other way to remove the redundancy?

**Comment by cabrerahector** [comment]
I'll need more details to help you out, @maustyle. Saying "there is no such a list item" doesn't help that much. You're basically asking me to guess why something doesn't work for you and that's simply not going to work for either of us.

For example, I'd like to know:

- Are you using the widget?
- Are you using the [wpp] shortcode?
- Are you using the wpp_get_mostpopular() template tag?
- What settings are you using?
- Etc.
