### ISSUE TITLE
Get posts that have featured images

### ISSUE THREAD

**Issue by GuerrillaCoder** [cabrerahector/wordpress-popular-posts#121]
Hi,

I want to build a slider based on the most popular posts featured images.  I am not sure of the best way to approach this.

I had a look at the code and I couldn't see anyway to add in an additional query param as i thought I could maybe add:

```
'meta_key' => '_thumbnail_id',
```

To the querys args.

The other way I thought was to return the raw data and filter out any posts without featured images but I also couldn't see anyway to return a post array instead of output html.

I am wary of doing anything that directly accesses database or alters core code as it mayl break my clients site if a future update conflicts.

What would you suggest is the best way to get a list of the most popular posts images without the "no thumbnail" images?

**Comment by cabrerahector** [comment]
Hi there!

Here's what I would do:

1. Use WPP's new [WPP_Query class](https://github.com/cabrerahector/wordpress-popular-posts/issues/110#issuecomment-244611584) to get an array of popular posts objects (while still a WIP, I don't think it'll change that much when officially released).
2. Use the [has_post_thumbnail](https://developer.wordpress.org/reference/functions/has_post_thumbnail/) function while iterating the array of popular posts objects to check whether the post has a featured image set: if it doesn't, skip it.

Hope that helps!
