### ISSUE TITLE
showing recently commented posts?

### ISSUE THREAD

**Issue by adamtri** [cabrerahector/wordpress-popular-posts#124]
Hello, is it possibile to configure the plugin in a way that is shows a list of *most recently commented* posts, instead of "mostly commented recent* posts?

**Comment by cabrerahector** [comment]
Hi there!

If you're using the widget, set _Sort posts by_ to _Comments_ and make sure that the "Display only posts published within the selected Time Range" checkbox is disabled.

If you're using either the [wpp shortcode](https://github.com/cabrerahector/wordpress-popular-posts/wiki/1.-Using-WPP-on-posts-&-pages) or the [wpp_get_mostpopular() template tag](https://github.com/cabrerahector/wordpress-popular-posts/wiki/2.-Template-tags#wpp_get_mostpopular), then set the _order_by_ parameter to "comments" and the _freshness_ parameter to 0.

**Comment by adamtri** [comment]
Hello, Thank you - I have these settings set.
But, as I understand (and see) it still shows the posts with the largest number of comments within the specified period of time. THey're ordered according to the number of comments (one with the largest number of comments is shown first).
What we wanted to achieve is to show a list of **recently commented** posts. I.e. when a new comment is posted to a post, the post appears on the list (even if it only has one comment and all the others - much more)?

**Comment by cabrerahector** [comment]
> What we wanted to achieve is to show a list of recently commented posts.

Ah, I see what you mean now. Thanks for the clarification! Unfortunately, that's something WPP can't do. It lists posts either by comments count or by views count. What you need is out of the scope of WPP.

I did a quick check on Google and while it appears that there are no plugins / widgets out there that list recently commented posts, this might be what you're looking for: [Show recent commented posts in WordPress](http://amansaini.me/show-recent-commented-posts-wordpress/).

If you want a widgetized/pluginized version of it, I am for hire :)

**Comment by adamtri** [comment]
OK. thanks for the link!
We've managed to set it up, using another method.
Thank you!,
Adam
