### ISSUE TITLE
Remove the word "Under" from Categories

### ISSUE THREAD

**Issue by Mikewalker24** [cabrerahector/wordpress-popular-posts#127]
Sorry if there's an obvious solution to this, but I can't find it. When including categories, the word "under" is inserted as a string. How can I remove this?

**Comment by HowToSolutions** [comment]
You can use _post_html_ parameter and then structure the HTML post for each element the way you like it. 

For example, in code below, word "under" is replaced with "in category":

`'post_html' => '<li><a href="{url}">{text_title}</a><span class="wpp-category"> in category {category}</span></li>'`
