### ISSUE TITLE
Do no display certain category in the category list 

### ISSUE THREAD

**Issue by djonatanb** [cabrerahector/wordpress-popular-posts#136]
I'm working with the wpp_get_mostpopular template tag. I'm aware of the option of setting 'cat' => -id but the problem is that it won't fetch any posts that belong to that category, I would like to fetch but not to show this specific category tag.

My situation is that I created a 'Featured' category to position some posts in the home page and I'm hiding that category from everywhere. 

do you have an idea ?

```
$featured = -1000;
$args = array(
    'range' => 'all',
    'wpp_start' => '<ul class="list-unstyled trending-posts">',
    'wpp_end' => '</ul>',
    'header' => 'Trending Articles',
    'thumbnail_width' => 82,
    'thumbnail_height' => 71,
    'stats_views' => 0,
    'stats_category' => 1,
    'header_start' => '<h3 class="title">',
    'header_end' => '</h3>',
    'post_html' => $html,
    'cat' => $featured
  );
```

**Comment by cabrerahector** [comment]
Hi there!

**The short answer:**
There's no way to do what you want without coding.

**The long answer:**
Problem is [WPP displays the first category that WordPress returns](https://github.com/cabrerahector/wordpress-popular-posts/blob/master/wordpress-popular-posts.php#L2326-L2339). In your case, it happens to be the Featured category. Unfortunately, there's no way to tell WPP "_hey, skip this category and show the next one, please._" so right now your only alternative is to use either of WPP filter hooks to [build your own HTML output](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#how-can-i-use-my-own-html-markup-with-your-plugin).

With version 4.0, WPP will display all categories and assign CSS classes to each of them so you can, for example, hide them using CSS.
