### ISSUE TITLE
Category & Post Display different result

### ISSUE THREAD

**Issue by jcloudsnetwork** [cabrerahector/wordpress-popular-posts#137]
Hi,

May I know why the popular post view display different result in category view vs article view?

Category view - https://hoganbo.com/hoganbo-journal/
Article view - https://hoganbo.com/blog/hoganbo-journal/articles/health/2017/04/12/policosanol-natural-ingredient-cuba-regulate-cholesterol/

Article view show correct count.

Thanks

**Comment by cabrerahector** [comment]
Hi there!

Actually, you're seeing two different WPP widgets:

- [Category.php widget](http://prnt.sc/f56prc).
- [Single.php widget](http://prnt.sc/f56q1q).

Notice how the **ids** are different?

**Comment by jcloudsnetwork** [comment]
Hi,

Thanks, I got it. 

I have 2 popular post widget, one for post and one for page and I found that the popular post widget in page sidebar only display "last 24 hours".

I want to confirm if both set time range as "all time", the view count are same right even different ID?

Thanks

**Comment by cabrerahector** [comment]
Yep, you can have both widgets use the exact same configuration if you want (and it that case both will show the exact same thing.)

**Comment by jcloudsnetwork** [comment]
Thanks for help.
