### ISSUE TITLE
Want to count the views of the custom taxonomy archive page

### ISSUE THREAD

**Issue by byron222** [cabrerahector/wordpress-popular-posts#139]
how can i count the views of the custom taxonomy archive page?

**Comment by cabrerahector** [comment]
Unfortunately that's not possible.

WPP explicitly excludes archive pages (category.php, tag.php, search.php,
etc) from the tracking process due to performance reasons. The plugin only
tracks single pages (single.php, single-custom-post-type.php, page.php,
etc.)
