### ISSUE TITLE
List popular categories

### ISSUE THREAD

**Issue by jontek2** [cabrerahector/wordpress-popular-posts#140]
I would love to be able to list the most popular categories based upon the number of views of posts/custom post-types.

**Comment by jontek2** [comment]
Got an SQL working:

`SELECT wp_terms.name,
  COUNT(wp_term_relationships.object_id) AS num_posts,
  SUM(pageviews) AS num_views
FROM wp_term_taxonomy
JOIN wp_terms ON wp_term_taxonomy.term_id = wp_terms.term_id
JOIN wp_term_relationships ON wp_term_taxonomy.term_taxonomy_id = wp_term_relationships.term_taxonomy_id
JOIN wp_posts ON (wp_term_relationships.object_id = wp_posts.id AND post_type='XXXX' AND post_status='publish')
JOIN (
       SELECT COUNT(*) pageviews, postid
       FROM wp_popularpostssummary 
       GROUP BY postid
     ) wp ON wp.postid = wp_posts.id
GROUP BY wp_terms.term_id
ORDER BY num_views DESC`

Replace XXXX with your post type/custom post type.

**Comment by cabrerahector** [comment]
Hey Jonathan!

That's a feature that falls outside of WPP's scope (to list popular posts.)
What you want sounds more like a add-on plugin / custom script: the data is
already there, what needs to be done is to create the means to read it and
somehow link the data to your categories.

**Comment by cabrerahector** [comment]
Nevermind, it seems you sorted it out already :P

**Comment by jontek2** [comment]
Yupp! Thanks for an awsome plugin :-)
