### ISSUE TITLE
Add the filter widget_wpp_args

### ISSUE THREAD

**Issue by Sorbing** [cabrerahector/wordpress-popular-posts#141]
Hi. Please add a hook for modifying the widget's arguments:
```
add_filter('widget_wpp_args','modify_widget_wpp_args');
```
Thanks.

**Comment by cabrerahector** [comment]
Hi there!

Quick question, why do you need this? What specifically are you trying to change?

**Comment by Sorbing** [comment]
I need to show popular posts in categories with a filter by current category.
Example:
```
if (is_category()) {
   $wppWidgetOptions['cat'] = get_queried_object_id();
}
```

**Comment by cabrerahector** [comment]
Ah, thanks! That won't be necessary though: [When viewing a taxonomy archive page have WPP list its most popular entries](https://github.com/cabrerahector/wordpress-popular-posts/issues/10).

**Comment by Sorbing** [comment]
> I replaced line 1551 of wordpress-popular-posts.php with the following code..
But, modifying the plugin code is not nice in WordPress..
