### ISSUE TITLE
WPP_query does not select correct language?

### ISSUE THREAD

**Issue by mittererr** [cabrerahector/wordpress-popular-posts#142]
I'm using WPP_query to show popular posts in my theme. Now posts are only selected in standard language (I'm using WPML Version 3.7.0)? Is it possible to select posts in current language by WPP_query()?

WordPress Version 4.7.5
WPP Version 4.0.0

**Comment by cabrerahector** [comment]
Hi Ronald!

No, it's not possible yet. With WPP v4 the entire plugin code was
refactored and some of the current features haven't been (fully)
implemented yet. This, as you already noticed, includes WPML support. It's
still a WIP.

If you _really_ need it, I suggest a downgrade to the latest official
release - at least until I push the multilanguage commits to Github and/or
officially release WPP v4, whatever happens first.
