### ISSUE TITLE
The plugin does not account for page requests made with Ajax.

### ISSUE THREAD

**Issue by httpiago** [cabrerahector/wordpress-popular-posts#147]
My website works with a dynamic page system that requests the new pages using Ajax in JavaScript, but I noticed that these requests are not counted by the plugin. I need this plugin but I think I'll have to do more myselfIs there anything I can do to change this? If not, I'll have to do my own visualization system.

**Comment by cabrerahector** [comment]
Well, of course. The plugin has no way to know that you're using AJAX to dynamically load posts and pages :P (and it's not how WordPress works out-of-the-box anyways.)

Fortunately, there's a way to work around this "limitation": [How-to: Updating the views count via AJAX](https://wordpress.org/support/topic/updating-the-views-count-via-ajax/).
