### ISSUE TITLE
Warning: htmlspecialchars()

### ISSUE THREAD

**Issue by andikart** [cabrerahector/wordpress-popular-posts#148]
Warning: htmlspecialchars(): charset `ANSI_X3.4-1968' not supported, assuming utf-8 in /xxx/xxx/public_html/wp-content/plugins/wordpress-popular-posts/wordpress-popular-posts.php on line 3383

my code:
```
                 <?php
	           global $post;
                  $postcat = get_the_category( $post->ID );
                  $args=array(
                    'cat' => $postcat[0]->term_id, // this is category ID
                    'orderby' => 'views',
					'stats_views' => 1,
					'limit' => 9,
					'order' => ASC,
					'range' => 'weekly',
				        'freshness' => 1,
					'post_type' => 'post',
					'title_length' => 25
                  );
		 wpp_get_mostpopular( $args );
              ?>
```

i try this code from [suport](https://wordpress.org/support/topic/show-most-popular-in-the-parentchild-category/)

```
// Get post data
    global $wp_query;
    $queried_object = $wp_query->get_queried_object();

    // Get post categories
    $categories = get_the_category( $queried_object->ID );

    // WPP paremeters
    $args = array(
        'range' => 'monthly',
        'limit' => 10,
        'post_type' => 'post'
    );

    // Post has at least one category assigned,
    // so let's use its ID to list the most popular
    // from that category
    if ( !empty( $categories ) ) {
        $args['cat'] = $categories[0]->term_id;
    }

    // Display popular posts list
    wpp_get_mostpopular( $args );
```

but still warning

**Comment by cabrerahector** [comment]
Hi Andika!

Here's the exact line of code that's triggering the warning message:

```php
$atts .= ' ' . $key . '="' . htmlspecialchars($arg, ENT_QUOTES, $encoding = ini_get("default_charset"), false) . '"';
```

This is the problematic bit: `$encoding = ini_get("default_charset")`. Your server is telling WPP to use the ANSI_X3.4-1968 character set which for some reason is triggering this warning message. Please get in touch with your hosting and ask them to change it to UTF-8 (or any other charset that suits the language you use on your site) and you should be good to go.
