### ISSUE TITLE
CSS styling gone after update -- child theme with dedicated 'wpp.css'

### ISSUE THREAD

**Issue by michal-dudek** [cabrerahector/wordpress-popular-posts#151]
Dear @cabrerahector 
First of all thanks a lot for creating and sharing with other your plugin, it is very useful!

Recently I have noticed that after an update of WPP my CSS styling is not applied anymore to the plugin although I am using a child-theme and I have a dedicated 'wpp.css' inside my theme.

1.) when I open my webpage with 'FF style editor' I can see the 'wpp.css', but not the one from the child theme (default)

2.) I have following 'wpp.css' files

blog/wp-content/themes/child-theme/wpp.css
blog/wp-content/plugins/wordpress-popular-posts/public/css/wpp.css

3.) when I copy the content from child-theme 'wpp.css' to child-theme 'style.css' all is correct

Before the update, all was working correctly. Have you experienced anything like that?

Thank you for your help!

Best regards,
MD

**Comment by cabrerahector** [comment]
Hi Michal!

Thanks for the detailed report. I'll look into it as soon as possible :)

**Comment by michal-dudek** [comment]
@cabrerahector I confirm, commit 3ea3511 fixes the issue. Thanks a lot for your help and prompt response!
