### ISSUE TITLE
Upgrade function not running on all sites in Multisite installation

### ISSUE THREAD

**Issue by gregsullivan** [cabrerahector/wordpress-popular-posts#153]
Hi Héctor,

I've been using your plugin on a client site for a number of years—thanks very much for all your work in maintaining it!

With the upgrade to 4.0.x, I've discovered a WordPress Multisite issue that has existed since version 3.0.0 (though it's tagged as 2.4.0 in the code):

```php
    /**
     * Checks if an upgrade procedure is required.
     *
     * @since	2.4.0
     */
    public function upgrade_check(){
        // Get WPP version
        $wpp_ver = get_site_option( 'wpp_ver' );
        if ( !$wpp_ver ) {
            add_site_option( 'wpp_ver', $this->version );
        } elseif ( version_compare( $wpp_ver, $this->version, '<' ) ) {
            $this->upgrade();
        }
    } // end upgrade_check
```

Here's the WordPress Codex describing `get_site_option`:

> This function is almost identical to get_option(), except that in multisite, it returns the network-wide option. For non-multisite installs, it uses get_option.

This means that the upgrade function will only run on the first site whose dashboard one visits after upgrading the plugin. After visiting that dashboard, the upgrade script will run for that site, and the network-wide option will be set, but only a single site's database will have been upgraded.

This became a major issue following the most recent update because it meant all sites but one on a multisite installation would still have the old table structure and wouldn't receive new data for that reason.

My temporary fix has been to update all instances of `get_site_option`, `add_site_option`, `update_site_option` and `delete_site_option` within the `upgrade()` and `upgrade_check()` functions to `get_option`, `add_option`, `update_option` and `delete_option`, respectively. This allowed me to trigger the database update across all sites, and the plugin is once again tracking page views on all sites.

Upgrades aside, it's possible there are other issues caused by the use of network-wide (rather than site-specific) options in the plugin, but I haven't been able to investigate in detail. (I also would better trust you to judge when a network-wide option would be more appropriate.)

Thanks again,

Greg

**Comment by cabrerahector** [comment]
Hi Greg,

Thanks for the heads up! I'll take another look to see of there are any other *_site_option function calls that need reviewing.

Once I'm done I'll push a new update.

In behalf of all Multisite WPP users, thank you!

**Comment by gregsullivan** [comment]
Awesome, thanks very much!
