### ISSUE TITLE
Missing data issue

### ISSUE THREAD

**Issue by Hachiko264** [cabrerahector/wordpress-popular-posts#158]
Hi, the plugin stopped to count the views on my posts for a few weeks. I updated the plugin, but got issues with the css. But the issue is the missing views that is making the listings wrong. I have the correct numbers in other plugins, but try to find out where I can update the correct numbers. Is this possible, or do I have to "deal with it", and have posts showing up wrong? 

Thank you

**Comment by cabrerahector** [comment]
Hi there,

Please [read here](https://wordpress.org/support/topic/how-do-i-manually-set-a-certain-number-of-views-for-a-post/).
