### ISSUE TITLE
Views data not updating

### ISSUE THREAD

**Issue by kingalbertarro** [cabrerahector/wordpress-popular-posts#159]
Hi! Good day,

I have some concern about my site. I just updated my plugin then after that the plugin stops getting the views. Hope you can help me.

**Comment by cabrerahector** [comment]
Hi there!

Good day to you, too.

Please share your site's URL so I can have a look, otherwise it's a bit difficult to tell what's going on.

**Comment by kingalbertarro** [comment]
Hi!

here's my site. hope you can do some check. i tried to reinstall the plugin
and delete the table in database still there's no Data yet. even i already
enable Ajaxtify.
http://borderlessryohei.com/

*King Albert*

**Comment by osterkraft** [comment]
Hi Hector, it seems that the upgrade sql command in "do_db_tables" doesn't work in all cases. I tried your suggestion [here](https://wordpress.org/support/topic/most-viewed-is-0/#post-9588028), but the problem is with the default value syntax. After reading [this thread](https://stackoverflow.com/questions/9192027/invalid-default-value-for-create-date-timestamp-field) I tried with values after 1970, but it didn't work either. The only way for me was to remove NO_ZERO_IN_DATE and NO_ZERO_DATE from SQL_MODE. But I guess this will affect quite many users, so another fix would be nice.

**Comment by cabrerahector** [comment]
Thanks for chiming in, @osterkraft!

You're righ, a few users have reported this and I wasn't sure what the problem was - I completely forgot about the no zero date thing! That would explain it!

I'll take a look into it as soon as possible.

**Comment by cabrerahector** [comment]
Hey @kingalbertarro,

Sorry for taking so long to reply back. Just checked your site and found something odd.

WPP uses a Javascript file to track the views of your posts and pages. When the plugin inserts it into the header section of your theme, it prepends a few variables required by the script to work ([example](https://prnt.sc/h5iw6w)).

In your case, the order of these has been inverted somehow (see https://prnt.sc/h5iv5g) and so the script that updates the views count never gets executed.

Got any idea of what might be causing this?

**Comment by kingalbertarro** [comment]
Hi Hector,

No worries, i know you're busy. About it, i really don't what cause it but
it might one of the plugins that making WPP malfunction. i might take a
look some of my plugins try to disable them. Thanks for the reply. I'll
reply once i fixed it or did not fix by myself.

*King Albert*

**Comment by kingalbertarro** [comment]
Hi Hector,

I already found the culprit. it seems that one of my plugins causing WPP to
malfunction. Thanks for helping me debug it.

Cheers!!

*King Albert*

**Comment by cabrerahector** [comment]
I'm glad you found the cause of the issue. Which plugin was it @kingalbertarro?

**Comment by kingalbertarro** [comment]
Hi Hector,

It was the "Head Cleaner" plugin. the culprit of the issue

*King Albert*
