### ISSUE TITLE
Custom field support

### ISSUE THREAD

**Issue by rhcarlosweb** [cabrerahector/wordpress-popular-posts#161]
Hello, first, thanks for this amazing plugin! second... sorry about my english 😢 

So, i think is a dump question, but i need know if i can do with this plugin.
I have a theme and i make a page to show the most popular posts based on views in the last month, and another page with most liked posts based on custom field 'likes'

Exist some way to do a filter to show the most liked posts in one period like your plugin do with views?

Thanks :)

**Comment by cabrerahector** [comment]
Hi there,

Unfortunately, there's no way to sort posts by likes or any other data at the moment.
