### ISSUE TITLE
Suddenly stopped showing posts

### ISSUE THREAD

**Issue by jesper-infoserv** [cabrerahector/wordpress-popular-posts#162]
Hi,
we've installed your plugin on our site and it have been working for some time. Suddenly it stopped showing any posts in the popular posts widget: http://dinavis.dk/nyheder/2017/11/14/kandidaterne-sloges-unges-gunst/ ("no data so far")

I've checked the popularpostsdata table and I can see lots of records from today and the past days, but it says "Looks like traffic to your site is a little light right now. 
Spread the word and come back later!" in WP no matter which time range i use. Only Hall of Fame shows posts. 

I have tried all the different settings and tried to ajaxify widget, but nothing works - and no debugging info shows up. Can you help?

- Jesper

**Comment by cabrerahector** [comment]
Hi Jesper,

It seems WPP couldn't upgrade its database tables.

Please log in into your hosting's control panel area and check that the _wp_popularpostssummary_ table is structured as follows:

- ID
- postid
- pageviews
- view_date
- view_datetime

If it's not, then please [follow these instructions](https://wordpress.org/support/topic/yet-another-no-data-problem/#post-9656330).

**Comment by jesper-infoserv** [comment]
Perfect, that fixed it.

Thank you!
