### ISSUE TITLE
Remove comma between categories

### ISSUE THREAD

**Issue by shelleyphant** [cabrerahector/wordpress-popular-posts#165]
Hi,

Is it possible to add some functionality to change the separator between category links? I'd like to have nothing between them, but it may also be useful to have the option of different characters to separate them.

**Comment by cabrerahector** [comment]
Hi @shelleyphant,

Sorry for taking so long to reply back.

Thanks for the suggestion! Off the top of my head I think this could be easily solved via a new filter hook (eg. `wpp_taxonomy_separator` or something like that). I'll think about it and if it gets implemented I'll make sure to leave a comment here.
