### ISSUE TITLE
exclude some part of a page not being cached

### ISSUE THREAD

**Issue by wobeng** [cabrerahector/wordpress-popular-posts#167]
Is there any way I can exclude some part of a page not being cached? In my site blog pages, there are places where I show data real-time. The content changes every minute.

**Comment by cabrerahector** [comment]
Hi Welby,

I'm not sure how this is related to WPP. Sounds more like a theme / your-caching-plugin problem to me to be honest, unless I'm missing something and in such case I'd like you to please elaborate a bit more on what the problem is so I may help out.

**Comment by wobeng** [comment]
hahah, forgive me, meant to post this at other plugin issues sections
