### ISSUE TITLE
How to create numerical order?

### ISSUE THREAD

**Issue by vanloc0301** [cabrerahector/wordpress-popular-posts#168]
I don't find any parameter in WP Popular Posts to create numerical order.

Look like this:

![capture](https://user-images.githubusercontent.com/4168981/34690297-23bb4d82-f4eb-11e7-9baf-7350adcb0466.PNG)

I found an example in https://github.com/cabrerahector/wordpress-popular-posts/wiki/6.-Styling-the-list
have this.

![687474703a2f2f63616272657261686563746f722e636f6d2f7770702d6f7264657265642d6c6973742d312e6a7067](https://user-images.githubusercontent.com/4168981/34690331-4af231e0-f4eb-11e7-97a2-dc6febd2c9c0.jpg)
![687474703a2f2f63616272657261686563746f722e636f6d2f7770702d6f7264657265642d6c6973742d322e6a7067](https://user-images.githubusercontent.com/4168981/34690334-4e8ca362-f4eb-11e7-8800-80d1222e6d4e.jpg)

Have any method to do it? Thank you very much.

**Comment by cabrerahector** [comment]
In the [examples](https://github.com/cabrerahector/wordpress-popular-posts/wiki/6.-Styling-the-list#examples) section you linked to there are instructions on how to convert the list into a numerical one. Read a bit and you'll find the answer you're looking for.

**Comment by vanloc0301** [comment]
@cabrerahector I don't use the widget. So, I can't edit HTML Markup.

I create a block have content like:
`[wpp post_type='post,page.post' thumbnail_width=75 thumbnail_height=60 wpp stats_views=0 limit=5 title_by_words=1 title_length=25]`

I create a new page have name "Homepage" and add this block to each tab.
![capture](https://user-images.githubusercontent.com/4168981/34695347-183bb5b6-f4fd-11e7-8bc5-29a0d0f99939.PNG)

In this picture, I have 3 tabs, each tab has difference `wpp` query.

So, I can't use widget for my case.

**Comment by cabrerahector** [comment]
Although the examples were made using the widget, you can still replicate them with the [[wpp] shortcode](https://github.com/cabrerahector/wordpress-popular-posts/wiki/1.-Using-WPP-on-posts-&-pages). All you need is a bit of patience and to read all the available documentation.

Take a look at _Settings > WordPress Popular Posts > Parameters_. The parameters you're looking for are `wpp_start`, `wpp_end` and `post_html`.

**Comment by vanloc0301** [comment]
Thank you very much. I don't know why it has broken my site.

I add the code: 
`[wpp post_type='post,page.post' thumbnail_width=75 thumbnail_height=60 wpp stats_views=0 limit=5 title_by_words=1 title_length=25 post_html='<li>{thumb} <a href="{url}">{text_title}</a></li>' wpp_start='<ol>' wpp_end='</ol>' ]`

First look like this:
![capture](https://user-images.githubusercontent.com/4168981/34696844-db0eda64-f502-11e7-8728-43167536a46c.PNG)

After adding this shortcode, it looks like:
![capture1](https://user-images.githubusercontent.com/4168981/34696850-e79e9292-f502-11e7-9134-baba011bbc06.PNG)

**Comment by cabrerahector** [comment]
Ok, the HTML part is ready. Now you need to work on the CSS part so it looks the way you want it to. Your theme won't turn it into the nice-looking numbered list automagically :P

Use the [examples](https://github.com/cabrerahector/wordpress-popular-posts/wiki/6.-Styling-the-list#examples) as a starting point to get the look & feel you're looking for. Alternatively, you might want to consider hiring someone to do it for you if you're not familiar with HTML & CSS in general and/or don't have the time to do it yourself.

**Comment by vanloc0301** [comment]
Thanks, @cabrerahector . I will try to do it.
