### ISSUE TITLE
Valid 'range' values?

### ISSUE THREAD

**Issue by MastaBaba** [cabrerahector/wordpress-popular-posts#170]
I just discovered that when I set the 'range' to 'last14days', the plugin actually reverts to 'daily'. Setting the range to 'monthly' works as expected.

What are acceptable 'range' values?

**Comment by cabrerahector** [comment]
Hi there!

Go to _Settings > WordPress Popular Posts > Parameters_ and you'll find the complete list of acceptable values for this and other parameters.

**Comment by MastaBaba** [comment]
I do?

I see: "last24hours", "last7days", "last30days", "all", "custom"

But, "monthly" also works, so this does not seem to be the full list.

I suppose I could generate a custom range, but a default range is neater.

**Comment by cabrerahector** [comment]
Ok, here's the deal:

- _daily_ = _last24hours_
- _weekly_ = _last7days_
- _monthly_ = _last30days_
- _all_
- _custom_

As you can see, _daily_, _weekly_ and _monthly_ are just aliases of _last24hours_, _last7days_ and _last30days_, respectively. It's not like there are some super secret time ranges no one should know about (what would I gain from hiding that from users anyway? :P)

**Comment by MastaBaba** [comment]
:) No one said anything about hiding.

Thanks!
