### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by scoobshub** [cabrerahector/wordpress-popular-posts#173]
Hi Hector! Thanks fro your great plugin :) 
Unfortunately on one of my sites, it generates this error:
```
SELECT p.ID AS id, p.post_title AS title, p.post_author AS uid, SUM(v.pageviews) AS pageviews FROM `wp_popularpostssummary` v LEFT JOIN `wp_posts` p ON v.postid = p.ID WHERE 1 = 1 AND p.post_type IN(%s) AND v.view_datetime > DATE_SUB('2018-01-27 17:27:21', INTERVAL 24 HOUR) AND p.post_password = '' AND p.post_status = 'publish' GROUP BY v.postid ORDER BY pageviews DESC LIMIT 10 OFFSET 0;
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%s) AND v.view_datetime > DATE_SUB('2018-01-27 17:27:21', INTERVAL 24 HOUR) AND ' at line 1
```

Is it normal?
Thanks a lot!

**Comment by cabrerahector** [comment]
Hey there!

No, it's not normal :P

Can't tell what's going on with so little info, though.

- Site's URL?
- WordPress version?
- Plugin version?

**Comment by scoobshub** [comment]
Thanks Hector for your fast reply!
Here's the details:
- WP 4.9.2
- WPP 4.0.13

I've sent you an email (via the form on you website) with the site url.
Thanks again for the support!!!
Andrea

**Comment by cabrerahector** [comment]
Hi Andrea,

Just checked your site and didn't where you're using WPP. Where are you seeing this error message?

**Comment by scoobshub** [comment]
Hi Hector, thanks again for taking the time to check out the site (where WPP is used mainly to populate the slider).
After several attempts trying to find out what as wrong, i discovered that the error was caused by the plugin "Debug Bar Slow Actions" :/ after deactivating it, everything went back to normal.

Thanks again and keep up the good work!

**Comment by cabrerahector** [comment]
Don't mention it. I'm glad to know you got it sorted out :)
