### ISSUE TITLE
Seeing "Sorry. No data so far" After Update (Plugin and WordPress)

### ISSUE THREAD

**Issue by VoltaicShock** [cabrerahector/wordpress-popular-posts#183]
I updated the plugin and now I am seeing "Sorry. No data so far".  It has been like this for a few days.  I have looked at the FAQ and tried what was suggested and nothing seems to be working.

It was working as of 5/22/2018.  After a plugin update and WordPress update it stopped working and hasn't been tracking for a few days.

**Comment by cabrerahector** [comment]
Hi Terry!

In order to help, I'm going to need some more details from you. Let's start with the basics:

- What's your site's URL?
- Do you have a caching plugin installed on your site?

**Comment by VoltaicShock** [comment]
Hello!

- www.teachablemommy.com
- No Caching plugins

**Comment by cabrerahector** [comment]
Thanks!

Ok, when the plugin tries to update the views count of any post or page on your site, the server responds with a **403 Access Forbidden** error (see [screenshot](https://prnt.sc/jmvshf)). Are you using a security / firewall plugin?

**Comment by VoltaicShock** [comment]
Here is a list of plugins that might be causing the issue:

HTTP headers to improve web site security
Security Headers
WP Cerber Security & Antispam

Could any of those be causing the issue?

Thank you for getting back to me so quickly.

**Comment by cabrerahector** [comment]
Can't tell, I don't use any of those :P If I had to guess, I'd say it's WP Cerber Security & Antispam.

A quick way to find out:

1. Disable all three plugins.
2. Visit any of your posts using your browser's Incognito mode (or another browser).
3. If your visit was registered (you'll see it in the Stats section) then it is one of these three plugins what's preventing WPP from updating the views count. Enable one of them and go back to step 2.

**Comment by VoltaicShock** [comment]
Sorry for the delay.  The issue was WP Cerber Security & Antispam.  There is a setting to turn off REST API in WordPress.  I turned off that feature and everything seems to be working now.

**Comment by cabrerahector** [comment]
Don't worry about it, I'm glad you were able to work it out :)

**Comment by VoltaicShock** [comment]
Thanks!  I am just glad it was something simple.
