### ISSUE TITLE
Version 4.1.0 - unexpected T_FUNCTION

### ISSUE THREAD

**Issue by Optimaximal** [cabrerahector/wordpress-popular-posts#186]
Version 4.1 will not load on our site (running WP 4.9.6).

Error:
`Parse error: syntax error, unexpected T_FUNCTION in /home/footshop/public_html/wp-content/plugins/wordpress-popular-posts/includes/class-wordpress-popular-posts-rest-controller.php on line 374`

**Comment by cabrerahector** [comment]
Sounds like you're running a *very* old PHP version there. Try upgrading to PHP 5.3 or newer and report back.
