### ISSUE TITLE
How do I display a list of tags from popular posts?

### ISSUE THREAD

**Issue by broros** [cabrerahector/wordpress-popular-posts#193]
how do I display a list of tags from popular posts?

get_tags()

**Comment by cabrerahector** [comment]
Hi @broros,

Well, assuming you're using the WPP widget:

1. Go to **Widgets > WordPress Popular Posts**.
2. Under **Stats Tag settings**, tick the **Display taxonomy** checkbox and hit the **Save** button to apply changes.
3. You'll see some new options appear under the **Display taxonomy** checkbox. Select **Tag** and hit the **Save** button once again to apply changes.

That's it!
