### ISSUE TITLE
Display posts view counts on top of the post

### ISSUE THREAD

**Issue by bradhuang9999** [cabrerahector/wordpress-popular-posts#194]
Since WordPress-popular-posts stores post view counts in the database. Can I display the post view counts in every post by editing my own theme?

**Comment by cabrerahector** [comment]
Sure you can! This is what you're looking for: [wpp_get_views()](https://github.com/cabrerahector/wordpress-popular-posts/wiki/2.-Template-tags#wpp_get_views).
