### ISSUE TITLE
Error in Rest controller broke my blog :(

### ISSUE THREAD

**Issue by tawqee3** [cabrerahector/wordpress-popular-posts#196]
My blog as well as others on the web have the following error:

Parse error: syntax error, unexpected T_FUNCTION in [path]/wp-content/plugins/wordpress-popular-posts/includes/class-wordpress-popular-posts-rest-controller.php on line 361

**Comment by cabrerahector** [comment]
Sounds like you're running an old version of PHP over there. WordPress Popular Posts [requires PHP 5.3](https://github.com/cabrerahector/wordpress-popular-posts#requirements) (or higher), so please try upgrading and report back the results.
