### ISSUE TITLE
401 http error 

### ISSUE THREAD

**Issue by WouterStraver** [cabrerahector/wordpress-popular-posts#197]
Hi, since 2 weeks anonymous users get http 401 errors when posting to /popular-post/. This isn't the case for logged in users. Any Idea how this certainly happend? Log views from setting is "everyone" 
website: https://renskroes.com

Thanks!

**Comment by cabrerahector** [comment]
Hi there,

Please check this [FAQ](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#im-getting-sorry-no-data-so-far-whats-up-with-that), pay special attention to the 5th bullet.

**Comment by WouterStraver** [comment]
Thanks for the quick response, I will try to find which plugin is doing this.
