### ISSUE TITLE
Count not accurate for infinite scroll pages

### ISSUE THREAD

**Issue by udezekene** [cabrerahector/wordpress-popular-posts#221]
I am using this for an infinite scroll page - kinda like QZ.com. However, it doesn't count the views while scrolling. Only on articles that were actually **clicked** and not when the article is _"scrolled to"_.

Is there a way to "manually" increase the view count by say 1?

**Comment by cabrerahector** [comment]
Hi there,

Yes, there is: [WordPress Popular Posts with an AJAX based website](https://wordpress.org/support/topic/wpp-with-an-ajax-based-site/).

**Comment by udezekene** [comment]
@cabrerahector Thanks for your response and for this really useful tool 🙌
I'll go try that.
