### ISSUE TITLE
Wordpress popular taxonomies

### ISSUE THREAD

**Issue by blackWhitePanda** [cabrerahector/wordpress-popular-posts#225]
I am struggling on how to list popular taxonomies. It would be great if the plugin could also  **log down the view count of taxonomies and show list of most popular taxonomies**.

I am working for a project about books. For "book"( which is the wordpress post type ), it has relation with many taxonomies, such as book_type, author, Publishing company, name of translator. Now, I can now show ranking of books by shortcodes with different book_type filter.
 
However, I cannot know the ranking for popular terms among author / Publishing company taxonomies. I wish, when user lands to single post page, not only pageview of post +1, but also the pageview of related taxonomies +1. So that, the popularity of author / Publishing company could be calculated and shown on homepage with a new shortcode.

Currently, the plugin use two database table to store view data of posts. It is really great for listing most popular books. The plugin allows me to rank most popular novel, Science Fiction, mystery, etc... (based on "book_type" taxonomy filtering). But, if it is expected to calculate the most popular taxonomies, 1-2 extra database tables may be required for storing the pageview of taxonomies and its item_id.

I guess you may wonder whether it is related to the plugin. I understand it is not the core feature of the plugin. However, it would be a very great add-on on current plugin. Since the plugin has mature caching mechanism and good sample code for referencing, it would be big benefit for developing wordpress popular taxonomies feature.

I was thinking about starting a new plugin for wordpress popular taxonomies. It would be large overhead of code if I also use wordpress-popular-posts plugin. Also, I am not familiar with caching (especially in memory cache) so it seriously affects the performance. 

If you agree on developing this feature and able to plan it on upcoming release, I would like to provide help on development, as much as I can.

**Comment by cabrerahector** [comment]
This has actually been requested before, and I have turned down the idea every time because -as you already pointed out- this kind of feature falls outside the original scope of the project.

On the other hand, I do think it would be useful so I'll think about it.

**Comment by blackWhitePanda** [comment]
If you think it is useful, the enhancement can be done by two steps. First, add pageview when user enter the single taxonomy page and able to show the popular taxonomies. Secondly, able to add pageview of related taxonomies when user enter the single post page.

Just let me know, when you think it is useful. I would like to participate to help construct business logic.
