### ISSUE TITLE
"Popular Posts" widget - current post link doesn't work

### ISSUE THREAD

**Issue by justanotheranonymoususer** [cabrerahector/wordpress-popular-posts#231]
Look at the screenshot below. I'm currently on the "Post2" page, and it has no "href" attribute in the "Popular Posts" widget and so is not clickable. I don't know whether it's on purpose, but it looks like a link, so it's counter intuitive, and it wasn't that way before.

![image](https://user-images.githubusercontent.com/5781692/65834721-88fabd00-e2e6-11e9-9b1e-3feb12dee8e6.png)

**Comment by justanotheranonymoususer** [comment]
I see it's on purpose:
https://github.com/cabrerahector/wordpress-popular-posts/blob/918ed643e910d6b526e9c5e9b3a2cf6ece10f078/changelog.md#320

> Removes href attribute from link when popular post is viewed.

It doesn't make much sense and is not consistent with the native wordpress widget of recent posts.

**Comment by justanotheranonymoususer** [comment]
OK, I see that it's "fixed" here:
https://github.com/cabrerahector/wordpress-popular-posts/commit/102f2e8e98342744c47513696ac6dc296730c464#diff-2e0956589ec8b870210a20b0a004c7cc

I don't know why the rel="nofollow", but it's good enough for me.
Any estimation for a new version release date?

**Comment by cabrerahector** [comment]
Hi there,

> I don't know why the rel="nofollow" (...)

For SEO purposes: when an indexing bot (eg. _googlebot_) checks the page it will find that there's a link that points to itself, creating a circular reference. By adding `rel="nofollow"` we ask it to ignore that link.

> Any estimation for a new version release date?

Been meaning to release 5.0 for some time now but work & life in general have gotten in the way. There are also some recent PRs I want to review as well before pushing 5.0 into the official repo. So -as you can probably imagine by now- 5.0 won't be officially launched anytime soon. I do plan to release it before the year ends though, just don't have a fixed date yet.

**Comment by justanotheranonymoususer** [comment]
Hi :)

> For SEO purposes: when an indexing bot (eg. _googlebot_) checks the page it will find that there's a link that points to itself, creating a circular reference. By adding `rel="nofollow"` we ask it to ignore that link.

Why would you think it will create a circular reference? Besides, the "recent posts" widget of wordpress doesn't add this, so why would you?

> 5.0 won't be officially launched anytime soon

I'll fix it locally. Thanks for the reply.

**Comment by justanotheranonymoususer** [comment]
P.S.

![image](https://user-images.githubusercontent.com/5781692/65837109-61aeea80-e2fc-11e9-8678-340ca37569ae.png)

**Comment by cabrerahector** [comment]
> Why would you think it will create a circular reference?

Because it does. As I explained earlier it's a link that points to itself, hence a circular reference.

After some thought though, it's pretty normal to find these kind of self-referencing links on basically every website out there. I don't think Google nor other search engines will necessarily penalize us for that so I might just remove that `rel="nofollow"` attribute from the link tag so thank you for bringing that up to my attention.

> Besides, the "recent posts" widget of wordpress doesn't add this, so why would you?

Following this kind of logic, maybe WPP shouldn't have the ability to display posts thumbnails because the stock Recent Posts widget doesn't? :P

**Comment by justanotheranonymoususer** [comment]
> hence a circular reference.

Well yeah, but the web is full of cycles. At the very least, you can go to the index page and then back, creating an A -> B -> A cycle, or as you name it, "circular reference".

> Following this kind of logic, maybe WPP shouldn't have the ability to display posts thumbnails because the stock Recent Posts widget doesn't? :P

Maybe. Depending on the use case, I guess, I never used them. I like your plugin since it looks like a natural addition to the default wordpress look and feel, as if it's part of the original setup.

Speaking of which, I also removed the `title="{$post_title_attr}"` attribute locally, since the Recent Posts widget doesn't have it (inconsistency), and it's silly anyway, since you show a tooltip with the exact same text as is already there.

**Comment by cabrerahector** [comment]
> I like your plugin since it looks like a natural addition to the default wordpress look and feel, as if it's part of the original setup.

That's the intention so thanks for the kind words. I'm glad you found my plugin useful! Then you'll probably like version 5.0 even more once you try it out (assuming you're not using the Github version already, that is.)

> Speaking of which, I also removed the `title="{$post_title_attr}"` attribute locally, since the Recent Posts widget doesn't have it (inconsistency), and it's silly anyway, since you show a tooltip with the exact same text as is already there.

There's a good reason why the `title` attribute is there: usability.

As you may have already noticed, the plugin offers the ability to shorten the title to _n_ characters. Say, for example, that the resulting HTML output would be something like this:

```
<ul class="wpp-list>
    <li>
        <a href="https://www.example.com" title="My very long post title">My very long...</a>
    </li>
</ul>

Without the `title` attribute, hovering on the link would display a tooltip with the text "My very long..." which isn't quite useful for the reader. The title`

**Comment by justanotheranonymoususer** [comment]
> I'm glad you found my plugin useful!

Thanks for creating it!

> the plugin offers the ability to shorten the title to _n_ characters

Then I'd say you should add a tooltip only if the title is truncated. Or at the very least only when the truncation is enabled.

**Comment by cabrerahector** [comment]
Yep, I was about to say that as well but hit the Comment button by mistake and even reopened the issue too :P I'll add that change to my already very long To-Do list.
