### ISSUE TITLE
The title_length parameter doesn't seem to work with {text_title}

### ISSUE THREAD

**Issue by cabrerahector** [cabrerahector/wordpress-popular-posts#241]
**Describe the bug**

The `title_length` parameter doesn't work with `{text_title}`. If you switch it with `{title}` then the title gets trimmed as expected.

**To Reproduce**

```php
$args = array(
    'limit' => 5,
    'range' => 'all',
    'post_html' => '<li class="list-group-item"><a class="h6 h6-md h6-lg" href="{url}">{text_title}</a></li>',
    'title_length' => 5
);
wpp_get_mostpopular($args);
```

**Expected behavior**

Title should be shortened in both cases.

**Environment:**

 - WordPress version: 5.3.2
 - PHP version: 7.2
 - Plugin version: 5.0.1

**Comment by leirap** [comment]
Thanks.
