### ISSUE TITLE
Consider adding a LICENSE or COPYING file to the repository root

### ISSUE THREAD

**Issue by ssokolow** [cabrerahector/wordpress-popular-posts#242]
**Is your feature request related to a problem? Please describe.**

Currently, GitHub does not recognize the licensing of this repository and incorporate it into its metadata.

**Describe the solution you'd like**

If you add a copy of the GPLv2 to the root of your repository with a filename `LICENSE` or `COPYING`, GitHub will recognize it and add a block to the repo header which indicates a GPL 2.0 license as well as a metadata field to search results like [this one](https://github.com/search?q=wordpress).

(Unless the license text diverges too much from what it recognizes, in which case, it will add a "View license" link instead.)

**Describe alternatives you've considered**

Leaving things as-is.

**Additional context**

Here's an example screenshot. WordPress's license file has been modified sufficiently for GitHub to not recognize it as the GPL2, so there's no metadata block in the results and the repo header just has a "View license" link, while the other two have license files it recognized.

![Screenshot_20200111_224722](https://user-images.githubusercontent.com/46915/72213870-43a57880-34ee-11ea-8a2b-10283fabba95.png)

I believe https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt is the file you have to rename to `LICENSE` or `COPYING` and add to your repo for GitHub to recognize it.

**Comment by ssokolow** [comment]
Oh, and, for the record, it makes sense that GitHub wouldn't recognize a modified file. The text of the GPL is licensed to you on the condition that it remains unmodified, while the WordPress repo prepends a bunch of stuff that the FSF says you should put in your source file headers instead.

It also makes sense that GitHub would require a `LICENSE` or `COPYING` file to display a license badge, because the GPL FAQ says that you're supposed to include a copy of the license with your project.

**Comment by cabrerahector** [comment]
Done! Thanks for the suggestion!
