### ISSUE TITLE
orderby popular

### ISSUE THREAD

**Issue by maxkopych** [cabrerahector/wordpress-popular-posts#245]
Can we order archive pages with string query...

Something like:

https//example.com/category/name/?orderby=popular

Thanks!

**Comment by cabrerahector** [comment]
With a bit of coding, yes, it's doable. This should get you on the right track: [How To: Sorting a custom query by views (All time, monthly, weekly, or daily)](https://wordpress.org/support/topic/how-to-sorting-a-custom-query-by-views-all-time-monthly-weekly-or-daily/).

**Comment by cabrerahector** [comment]
As a bonus hint, combining the above with this -with a few minor tweaks- should do the trick: [Sort by meta key on archive page](https://wordpress.stackexchange.com/questions/215368/sort-by-meta-key-on-archive-page).
