### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by broros** [cabrerahector/wordpress-popular-posts#246]
**Describe the bug**
I am getting an error in php on line ( foreach ($post_tags as $tag) )

```
PHP Warning:  Invalid argument supplied for foreach() in /home/myusername/public_html/wp-content/plugins/custom-popular-posts/custom-popular-posts.php on line 31
```

**To Reproduce**
```
foreach ($popular_posts->get_posts() as $popular_post) {
            $post_tags = get_the_tags($popular_post->id);

            foreach ($post_tags as $tag) {
                if (! isset($tags[$tag->slug])) {
                    $tags[$tag->slug] = array(
                    'id' => $tag->term_id,
                    'name' => $tag->name,
                    );
                }
            }
        }
```

**Screenshots**

**Environment:**
 - WordPress version: [e.g. 5.2.2]
 - PHP version: [e.g. 7.3]
 - Database version: [e.g. MariaDB 10.3]
 - Plugin version: [5.0]

**Comment by cabrerahector** [comment]
Unfortunately you'll have to reach out to whoever coded that because the plugin you're using is not the official WordPress Popular Posts plugin:

> /wp-content/plugins/custom-popular-posts/custom-popular-posts.php

**Comment by broros** [comment]
this is the code you gave me to display popular post tags

**Comment by cabrerahector** [comment]
Is that so? I don't remember ever writing that so I'm curious, mind telling me when exactly I did that?

Also, and assuming I actually wrote that code, you'll need to share the entire content of the plugin (not just that code snippet) if you want to get any help from me. What you posted isn't enough to tell what's going on.

**Comment by broros** [comment]
I updated, I this something to do with PHP 7.3?

**Comment by cabrerahector** [comment]
No, it's not that. I believe that one of your popular posts has no tags assigned to it which would explain why PHP complains about `$post_tags` not being a valid `foreach` resource.

Try this:

```php
$post_tags = get_the_tags($popular_post->id);

if ( ! $post_tags || is_wp_error($post_tags) ) {
    continue;
}

// rest of the code continues below
```
