### ISSUE TITLE
Does this plugin work with Nginx's fastcgi cache?

### ISSUE THREAD

**Issue by sewalsh** [cabrerahector/wordpress-popular-posts#253]
Will this plugin record and display post view counts even if there's a server side cache?

**Comment by cabrerahector** [comment]
As long as the cache is regenerated at least once per day then yes it should work. Check this FAQ for more details: [Is WordPress Popular Posts compatible with caching plugins?](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#is-wordpress-popular-posts-compatible-with-caching-plugins)

**Comment by sewalsh** [comment]
Fantastic, going to try this out.
