### ISSUE TITLE
Disabling Javascript

### ISSUE THREAD

**Issue by AvdLee** [cabrerahector/wordpress-popular-posts#254]
Hey there!

First of all, thanks for creating the plugin. It's great and I'm using it with a lot of joy. However, I'm currently trying to remove as much Javascript from my website as possible.

I was wondering, for what reason this plugin is using Javascript (wpp-5.0.0.min.js) and could I disable it without breaking the plugin?

Thanks!

**Comment by cabrerahector** [comment]
Hi Antoine, glad to know you're enjoying the plugin :)

Regarding the JS file, WPP uses it for various things but mainly to keep track of your post/page views. Also it's only a few KBs in size (less than 5 KBs if I remember correctly?) so you wouldn't be gaining a lot of performance from removing it.

**Comment by AvdLee** [comment]
Thanks for the reply, @cabrerahector. Makes sense! In that case I can't do without it as well.
I've now optimized it through Autoptimize to at least have less requests going out.

Thanks!
