### ISSUE TITLE
Replace JS lazy loading with native lazy loading

### ISSUE THREAD

**Issue by cabrerahector** [cabrerahector/wordpress-popular-posts#257]
As of April 7th, 2020, most major browsers have adopted the new [native lazy loading feature](https://caniuse.com/#feat=loading-lazy-attr) introduced by Google. Let's have WordPress Popular Posts use that to lazy load thumbnails instead of the current JS based implementation.

**Comment by Wendihihi** [comment]
When you change it to the native lazy loading feature please add an option enable/disable lazy load via the plugin. 97% of my website visitors use a mobile device and it would affect 17% of the visitors.

**Comment by cabrerahector** [comment]
> ... please add an option enable/disable lazy load via the plugin.

There _is_ already an option for this in **Settings > WordPress Popular Posts > Tools** under **Thumbnails**.

The native Lazy Load feature shouldn't cause issues for browsers that don't support it though (eg. Safari, Internet Explorer, etc.) In such cases I believe the browser will just ignore the `loading` attribute as it doesn't know what it is and continue to load the thumbnails normally. (So the option to enable/disable lazy loading might not even be needed any more after all but I'll leave it there for at least one or two more releases just to be sure.)
