### ISSUE TITLE
Except doesn't show

### ISSUE THREAD

**Issue by ymauron** [cabrerahector/wordpress-popular-posts#259]
Hi, 

On my wpp install, popular post are displayed but not with excerpt, despite the option being activated.

- Here is the page on which the shortcode is used : https://grandir.app under "Les sujets du moment"
- The shortcode I used is : [wpp limit=10 excerpt_by_words=1 excerpt_length=40 excerpt_format=1 range="last30days" stats_views=1 order_by="views" stats_views=0]

**Comment by cabrerahector** [comment]
Hi @ymauron,

By default, the [wpp] shortcode doesn't include the excerpt as part of its HTML output (see `post_html` parameter.)

To have it display the parameter, use the `{summary}` Content Tag in conjunction with the `post_html` parameter, like so for example:

```
[wpp limit=10 excerpt_by_words=1 excerpt_length=40 excerpt_format=1 range="last30days" stats_views=1 order_by="views" stats_views=0 post_html="<li>{thumb} {title} <div class='wpp-excerpt'>{summary}</div><div class='wpp-meta post-stats'>{stats}</div></li>"]
```

By the way, you have `stats_views` twice in there.

**Comment by ymauron** [comment]
Hi, 

Many thanks for that... I would have red the doc properly :)

Have a nice day !
