### ISSUE TITLE
Increment View Count on Quick View Modal or Button Click

### ISSUE THREAD

**Issue by dvrcthewrld** [cabrerahector/wordpress-popular-posts#260]
It would be beneficial to have a straightforward method of triggering a view count update / increment when a "quick view" is used.  For example, if I use a quick view plugin on my WooCommerce store, I'd like that view to be counted.

It would be nice if I could just include a small script in that Quick View modal that would trigger an increment of the view count.

Maybe this is basically possible as of now, but I've just missed it.  If so, please, do let me know.  Thanks.

**Comment by cabrerahector** [comment]
Hi there,

Yes, this has been asked before and yep there is: [WPP with an AJAX-based site](https://wordpress.org/support/topic/wpp-with-an-ajax-based-site/). That should get you on the right track but if you have any questions don't hesitate to ask.
