### ISSUE TITLE
INCREMENT PAGE VIEW COUNT REST API

### ISSUE THREAD

**Issue by maykon-oliveira** [cabrerahector/wordpress-popular-posts#263]
I was looking for a way to increment page view count through [REST-API-Endpoints](https://github.com/cabrerahector/wordpress-popular-posts/wiki/8.-REST-API-Endpoints), but there is nothing talking about that feature or how could I do. However I found a function in [RestController](https://github.com/cabrerahector/wordpress-popular-posts/blob/336db687f2c7c3435a7184acb604590c7f63a4fe/src/Rest/Controller.php#L121) source code that do that, so I am opening a issue to you improve the wiki, and describe it how a client can increment page view count throught API.

`$ POST htts://localhost:8080/wp-json/wordpress-popular-posts/v1/popular-posts?wpp_id=623`

**Comment by cabrerahector** [comment]
Hi Maykon,

There is at least one issue here that does talk about it: [Increment View Count on Quick View Modal or Button Click](https://github.com/cabrerahector/wordpress-popular-posts/issues/260). That issue links to the Support forum where there's a pinned topic that explains how to do it as well: [WPP with an AJAX-based website](https://wordpress.org/support/topic/wpp-with-an-ajax-based-site/).

Try using different search terms next time :P
