### ISSUE TITLE
Popular Posts in Headless mode

### ISSUE THREAD

**Issue by mathewtrivett** [cabrerahector/wordpress-popular-posts#264]
Is there a way to use Wordpress Popular Posts in headless mode. We are building a site using Wordpress as our CMS but with a React.js frontend. Is it possible to write back meta data on posts, pages and custom posts etc. when different pages are loaded to track views and this be consumed by Wordpress Popular Posts?

Thanks

**Comment by cabrerahector** [comment]
Hi there,

You can [update the views count of your posts and pages via AJAX](https://wordpress.org/support/topic/wpp-with-an-ajax-based-site/#post-11722489) using the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) whenever a post/page is loaded by your app.

**Comment by mathewtrivett** [comment]
Amazing thanks so much for the speedy response and for making this plugin 🙌
