### ISSUE TITLE
Error happens when ver 5.2.0 active

### ISSUE THREAD

**Issue by taketake2145** [cabrerahector/wordpress-popular-posts#266]
**Describe the bug**
error happens when ver 5.2.0 active

**To Reproduce**
```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function replaceChild() on null in {path}/wp-content/plugins/wordpress-popular-posts/src/Front/Front.php:141
Stack trace:
#0 {path}/wp-includes/class-wp-hook.php(287): WordPressPopularPosts\Front\Front-&gt;convert_inline_js_into_json('&lt;script type='t...', 'wpp-js', 'https://www.sim...')
#1 {path}/wp-includes/plugin.php(206): WP_Hook-&gt;apply_filters('&lt;script type='t...', Array)
#2 {path}/wp-includes/class.wp-scripts.php(400): apply_filters('script_loader_t...', '&lt;script type='t...', 'wpp-js', 'https://www.sim...')
#3 {path}/wp-includes/class.wp-dependencies.php(116): WP_Scripts-&gt;do_item('wpp-js', 0)
#4 {path}/wp-includes/class.wp-scripts.php(643): WP_Dependencies-&gt;do_items(Array, 0 in <b>{path}/wp-content/plugins/wordpress-popular-posts/src/Front/Front.php</b> on line <b>141</b><br />
```

**Expected behavior**
No error

**Screenshots**

**Environment:**
 - WordPress version: 5.4.2
 - PHP version: 7.4.4
 - Database version: MySQL5.6
 - Plugin version: 5.2
 - Active plugins: Advanced Custom Fields, Akismet Anti-Spam, AMP, Category Order and Taxonomy Terms Order, Compress JPEG & PNG images, Contact Form 7, No Category Base (WPML), Search Regex, SiteGuard WP Plugin

**Additional context**
I like this plugin wordpress-popular-posts.
Sorry i have no idea to fix it up.
But I hope i can update it.

Regards

**Comment by cabrerahector** [comment]
Hi @taketake2145,

Could you please disable all of your plugins (except for WordPress Popular Posts) and check whether the issue still remains or not?

**Comment by taketake2145** [comment]
Thank you to reply quickly,

I disabled all of my plugins except wpp. But the issue still remains.
And I tried to change a few themes. but the issue is same. i mean still remains.

**Comment by cabrerahector** [comment]
Alright, thanks for the update.

For the time being, please [downgrade to version 5.1.0](https://wordpress.org/support/topic/critical-error-after-plugin-update-2/#post-13111106) while I work on a fix.

**Comment by taketake2145** [comment]
Okey, i use 5.1.0 till then.
Regards

**Comment by cabrerahector** [comment]
Hey @taketake2145,

Please try [this](https://wordpress.org/support/topic/critical-error-after-plugin-update-2/#post-13111638) and report back your results.

Thanks in advance!

**Comment by taketake2145** [comment]
Hi @cabrerahector,

I tried. Amazing! No error!!
Now is no data of wpp. but soon it will show up.

Thank you so much!
