### ISSUE TITLE
Function exists, but are there posts?

### ISSUE THREAD

**Issue by evandiamond** [cabrerahector/wordpress-popular-posts#271]
Right now I have code like this ... 

```
<div class="frame">
    <?php if (function_exists('wpp_get_mostpopular')) : ?>
    <?php $args = array(...); ?>
    <?php wpp_get_mostpopular($args); ?>
    <?php endif; ?>
</div>
```

Would it be possible to put that `<div class="frame">` inside the function exists so if no items are found, the frame around it doesn't show?

```
<?php if (function_exists('wpp_get_mostpopular')) : ?>
    <?php $args = array(...); ?>
    <?php if (has_posts) : ?> // something like this
        <div class="frame">
            <?php wpp_get_mostpopular($args); ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
```

I'd rather not show my custom widget rather than showing `Sorry. No data so far.`

Appreciate your help in advance.

**Comment by cabrerahector** [comment]
Hi @evandiamond,

That would be possible if the [wpp_get_mostpopular()](https://github.com/cabrerahector/wordpress-popular-posts/wiki/2.-Template-tags#wpp_get_mostpopular) function _returned_ data but it doesn't. It _echoes_ a list of popular posts or a "Sorry, no data so far" message if no posts match the selected criteria.

Possible workarounds:

- You could use the [wpp_no_data](https://github.com/cabrerahector/wordpress-popular-posts/wiki/3.-Filters#wpp_no_data) filter hook to return an empty string, or
- You could use the [WordPressPopularPosts\Query](https://github.com/cabrerahector/wordpress-popular-posts/blob/5.2.4/src/Query.php) class to fetch a list of popular posts directly from the database and use that to build your popular posts list with your own logic.

**Comment by evandiamond** [comment]
@cabrerahector Thanks for the reply!

Would this be acceptable?

```
<?php
if (is_plugin_active('wordpress-popular-posts/wordpress-popular-posts.php')) {
    $popular_posts = new WordPressPopularPosts\Query($args);
    $results = $popular_posts->get_posts();
    foreach ($results as $popular_post) {
        $post = get_post($popular_post->id);
        setup_postdata($post);

        echo get_the_title();
    }
    wp_reset_postdata();
} ?>
```

I'm assuming things like `post_html`, `thumbnail_height` and `thumbnail_width` will not work when querying this way? Is that correct?

**Comment by cabrerahector** [comment]
> Would this be acceptable?

Yep, looks good to me.

If you're using namespaces with your theme then you may need to add a backslash before the WordPressPopularPosts namespace or else you'll get a PHP error:

```php
$popular_posts = \WordPressPopularPosts\Query($args);
```

If you aren't using namespaces with your theme then it won't be necessary.

> I'm assuming things like `post_html`, `thumbnail_height` and `thumbnail_width` will not work when querying this way? Is that correct?

Yes, that's correct. If you're familiar with the [WP_Query](https://developer.wordpress.org/reference/classes/wp_query/) class before then this is pretty much like it: the `WordPressPopularPosts\Query` class also returns an array of popular posts objects and that's it. It's up to you to build the HTML output however you like it using the data provided by the class.

So, following your original question:

```php
<?php
if (is_plugin_active('wordpress-popular-posts/wordpress-popular-posts.php')) {
    $popular_posts = new WordPressPopularPosts\Query($args);
    $results = $popular_posts->get_posts();

    // We have some posts to show, let's build the list
    if ( is_array($results) && ! empty($results) ) {
        ?>
        <div class="frame">
            <?php
            foreach ($results as $popular_post) {
                $post = get_post($popular_post->id);
                setup_postdata($post);

                echo get_the_title();
            }
            wp_reset_postdata();
            ?>
        </div>
        <?php
    }
}
?>
```

**Comment by evandiamond** [comment]
Perfecto. Thanks for the quick replies. You're a good man, Charlie Brown.
