### ISSUE TITLE
Raiting by Category

### ISSUE THREAD

**Issue by diasasx** [cabrerahector/wordpress-popular-posts#281]
Hi, i have a website [https://goblinsguide.com/].
I d like to ask you to make a little modification for me.
I have a category->posts scheme
So I need from you a 3rd table to store my category raitings,
all posts views in every category->views sum by category
and to display it where i need.
ready to pay for that, if it not sky high ^) 
thx in advance

p.s - with no load for my server : ))

**Comment by cabrerahector** [comment]
Hi @diasasx,

This isn't the right place to request freelance work. Please use my [contact form](https://cabrerahector.com/about#say-hi) to do so.
