### ISSUE TITLE
Label on each post

### ISSUE THREAD

**Issue by mkkb917** [cabrerahector/wordpress-popular-posts#285]
Hello
Hope you doing fine in this pendamic 
sir 
I have a suggestion of adding a simple caption of numbering each thumbnail that I configure in tiles using the popular posts
Please attach the sample image for reference
Is there any way to do this labeling please reply me wth procedure
regards
<img width="982" alt="Screenshot 2021-03-08 194812(1)" src="https://user-images.githubusercontent.com/55022641/113409378-98bafc00-93ca-11eb-9748-56fbce16be9e.png">

**Comment by cabrerahector** [comment]
Hi @mkkb917,

There are a few examples on the [Styling the List](https://github.com/cabrerahector/wordpress-popular-posts/wiki/6.-Styling-the-list) section that show how to add a number next to each popular post, specifically:

- [CSS3 Ordered List #1](https://github.com/cabrerahector/wordpress-popular-posts/wiki/6.-Styling-the-list#css3-ordered-list-1)
- [CSS3 Ordered List #2](https://github.com/cabrerahector/wordpress-popular-posts/wiki/6.-Styling-the-list#css3-ordered-list-2)
- [CSS3 Ordered List #3](https://github.com/cabrerahector/wordpress-popular-posts/wiki/6.-Styling-the-list#css3-ordered-list-3)

You can use those as a starting point to learn how to display the position number. Once that's done, to display the list as a grid as shown on the screenshot you can either use [CSS Grids](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) or [Flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox).

If you'd prefer having someone implement all this for you I'm available for freelance work.

Please let me know if you have any other questions.
