### ISSUE TITLE
Russian encoding problem 

### ISSUE THREAD

**Issue by seryogakovalyov** [cabrerahector/wordpress-popular-posts#292]
After updating to version 5.3.4, the Russian language in the view is displayed incorrectly 

![2021-07-04](https://user-images.githubusercontent.com/25284684/124372489-d877d500-dc92-11eb-8e82-7568a2030ed3.png)

**Comment by cabrerahector** [comment]
Hi @seryogakovalyov,

This should have been fixed with the latest release. Please update as soon as possible.
