### ISSUE TITLE
Custom Field Thumbnails Not Caching

### ISSUE THREAD

**Issue by h00die** [cabrerahector/wordpress-popular-posts#313]
**Describe the bug**
Internal blog site, not accessible to the Internet. I have GD installed. Pick image from: Custom field, Lazy load: No, Custom field name: `wpp_thumbnail`, Resize image from Custom field?: Yes.

Popular Posts listing is not caching the images and serving local, instead direct linking to image in `wpp_thumbnail` field.

**To Reproduce**
1. Create a post
2. Set the `wpp_thumbnail` to an image and publish
3. view homepage
4. see image is not cached locally but linked to directly

**Expected behavior**
The image is supposed to be caching locally, not direct linking.

**Screenshots**

Settings:

![image](https://user-images.githubusercontent.com/752491/141611321-f84120dc-f691-4b1b-8bf1-a257d00d5c56.png)

![image](https://user-images.githubusercontent.com/752491/141611330-f62ca885-1968-4350-8909-a5ce4b387e17.png)

Widget:

![image](https://user-images.githubusercontent.com/752491/141611337-e6d4da43-76a2-4198-979d-4f070772194e.png)

Example post:

![image](https://user-images.githubusercontent.com/752491/141611350-d90c54e9-f172-43d3-9196-fcedc7a3944e.png)

Image linked directly:

![image](https://user-images.githubusercontent.com/752491/141611363-4e5ea9cc-2a58-44a5-b273-173fabde4120.png)

**Environment:**
 - WordPress version: 5.4.1 ( i tried a 5.8.2 as well, same result)
 - PHP version: 7.4.3
 - Database version: 10.3.22-MariaDB-1ubuntu1
 - Plugin version: 5.3.2
 - Active plugins: None (akismet not active, hello dolly not active)

**Comment by cabrerahector** [comment]
Hi @h00die,

The `https://i2.wp.com` domain in the URL is not WordPress Popular Posts' doing though. Another plugin (or your hosting provider? Are you using WPP on wordpress.com?) is caching WPP's thumbnails on `wp.com`. Try following the [troubleshooting instructions](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#initial-troubleshooting) to find out if it's a plugin or your hosting provider doing this.

**Comment by h00die** [comment]
Just for clarity, I'm self hosting. I picked that image as just a random image on the Internet that was hosted and could be accessed. I've tried images hosted on another internal server with no success as well

**Comment by cabrerahector** [comment]
Alright so I tried to reproduce the issue on localhost and WordPress Popular Posts (latest version) worked as expected: it generated a thumbnail from the provided URL and stored it on /wp-content/uploads/wordpress-popular-posts/.

Thumbnail Settings:

![wpp--tools--thumbnail-settings](https://user-images.githubusercontent.com/3186556/141648844-9fcca3bf-76b0-4844-9cd7-7418ef440cde.png)

Post Edit screen:

![post-edit-screen--wpp_thumbnail-custom-field](https://user-images.githubusercontent.com/3186556/141648851-5dce3330-a492-48ac-bac1-087084b61f6c.png)

WPP block on the front-end:

![wpp-widget-on-front-end](https://user-images.githubusercontent.com/3186556/141648855-48f4b584-0537-48b1-9839-f774eaaa3f66.png)

So I'm not really sure what's going on on your side.

I did my testing with the latest version of the plugin (5.4.2) and the latest WordPress release (5.8.2) but I can't say that that'll make a difference, I don't recall having changed anything custom field related between 5.3.2 (the version you have) and 5.4.2.

**Comment by h00die** [comment]
Seems to be working, thanks! Not exactly sure why it wasn't for me to start with

**Comment by cabrerahector** [comment]
A glitch in the Matrix. It happens :P

Thanks for reporting back, and have a nice week!
