### ISSUE TITLE
Missing Performance Feature from Wiki

### ISSUE THREAD

**Issue by pacifier007** [cabrerahector/wordpress-popular-posts#326]
There's a featured mentioned in the performance section of wiki to batch update object cache instead of logging views right away.

https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance#caching

I tried it but it doesn't work. Looks like there's no code for it. In Front.php I see there is no code to batch update, it updates right away.

Am I missing something or this feature not done yet (will release in future update?)

**Comment by pacifier007** [comment]
Sorry my bad. Thanks for clarifying. I was using a custom JS implementation that doesn't use REST end-point, but the AJAX endpoint.

Is the AJAX code still used anywhere or it is deprecated? 

You can close it now. Thanks.

**Comment by cabrerahector** [comment]
If by "AJAX code" you're referring to [this](https://wordpress.org/support/topic/wpp-with-an-ajax-based-site/) then it should still work, yeah. Haven't tested it in a while though.

If it's not that then please share more details.

**Comment by pacifier007** [comment]
That's correct. Or specifically this one: https://wordpress.org/support/topic/updating-the-views-count-via-ajax/

Basically, it uses the wp_ajax_nopriv_update_views_ajax which uses the update_views method in Front.php. 

It's a very clear switch to REST for me. Not a problem at all, was just letting you know if that's some dead code in Front.php, that can be cleaned up :)

**Comment by cabrerahector** [comment]
Ah, yeah that's _super_ old hahaha.

WPP has been using the REST API since May 2018, nearly four years ago now :) All the `admin-ajax.php` stuff has been removed from the plugin since then.
