### ISSUE TITLE
Visit number missing in the api

### ISSUE THREAD

**Issue by titosobabas** [cabrerahector/wordpress-popular-posts#327]
I have the next wordpress-popular-posts api running on my website:

`https://www.laciudadbabasonica.com/wp-json/wordpress-popular-posts/v1/popular-posts?limit=5`

The visit number is missing in the final json result.

I want to get the vistit number  of each post from the api but it doesn't exist, as you can see in the image below (taken from the dashboard of the plugin) 

![image](https://user-images.githubusercontent.com/18486020/157344253-7d7a8edc-43bb-4436-a21a-fd042895df30.png)

**Comment by cabrerahector** [comment]
Hola Fernando,

> The visit number is missing in the final json result.

No, it's not :P It's the `pageviews` parameter what you're looking for.

![image](https://user-images.githubusercontent.com/3186556/157439994-623ddbe0-65e0-43ed-aca6-352c21ecad66.png)
