### ISSUE TITLE
Get posts data

### ISSUE THREAD

**Issue by mcDialogs** [cabrerahector/wordpress-popular-posts#328]
**Is your feature request related to a problem? Please describe.**
It doesn't appear that there is a way to query the rest api for a list of popular posts with multiple taxonomies

**Describe the solution you'd like**
A way to query the api with multiple taxonomies OR a function similar to wpp_get_mostpopular() that returns an array of posts rather than echoing out those posts to the page.

**Comment by cabrerahector** [comment]
Note though that this class is not meant for public usage as it can (and will) change without prior notice.

If you use it do keep an eye on the changelog to make sure you're up to date with potential future breaking changes.
