### ISSUE TITLE
Is it possible to mark popular articles in archive.php?

### ISSUE THREAD

**Issue by rsmouk** [cabrerahector/wordpress-popular-posts#331]
Is there a possibility to check if an article in the archive is popular?
For example: When viewing the latest articles published on the site, I want to add a hot class to the popular article in the list
```
<ul class="last-articles">
<li class="item"> article 1</li>
<li class="item"> article 2</li>
<li class="item"> article 3</li>
<li class="item hot"> article 4</li>  👈
<li class="item"> article 5</li>
</ul>
```

**Comment by cabrerahector** [comment]
Hi @rsmouk,

Yeah, I guess so. You need to define what makes a post "popular" though.

For example, you could add that `hot` class to a post if it exceeds *N* views:

```
<li class="item <?php echo ( function_exists('wpp_get_views') && wpp_get_views( get_the_ID(), 'all', false) >= 1000 ) ? 'hot' : ''; ?>"> ... </li>
```

**Comment by rsmouk** [comment]
@cabrerahector  Thank you for your response and your support for this special addition.

about the question: I do not want to limit the number of visits.
I want to add a class to the trending article during the day, or the week .. regardless of the number of visits.
I hope you understand me

**Comment by cabrerahector** [comment]
Well, if you don't want to set a minimum amount of views to mark a post as "hot" then another thing you could do is get a list of the most popular posts from the last 24 hours (eg. via the [\WordPressPopularPosts\Query](https://github.com/cabrerahector/wordpress-popular-posts/blob/5.5.1/src/Query.php) class), then compare their IDs with the IDs from the posts from your archive list and mark the ones that match as "hot".

**Comment by rsmouk** [comment]
@cabrerahector 
I am a beginner in this field
Can you give me the full code?
With my respects.

**Comment by cabrerahector** [comment]
I'm available for freelance work if you need help with this if you're interested.

**Comment by rsmouk** [comment]
I send you an email , please cheek
