### ISSUE TITLE
Add hits

### ISSUE THREAD

**Issue by blacknightt1** [cabrerahector/wordpress-popular-posts#332]
Hello Thank you for your good plugin And I have been using this plugin for several years and it is very effective

But I want to manually increase the number of views per post In which part of the plugin should I do this? For example, post 1, which was visited by 20 people, I want to do 200 manually

**Comment by cabrerahector** [comment]
Hi @blacknightt1,

WordPress Popular Posts stores views data in two separate database tables:

- **wp_popularpostsdata**: here you’ll find the All-Time (total) views count.
- **wp_popularpostssummary**: the views count of the last 24 hours/week/month/etc.

Depending on how you're using WPP you may need to edit one or both tables.

If you have any further questions don't hesitate to ask.

**Comment by cabrerahector** [comment]
Yes, it's possible. You need to edit the views data directly in the database as I mentioned earlier. Please see my previous comment for more details.

**Comment by blacknightt1** [comment]
Thank you for your help
My problem was solved
