### ISSUE TITLE
 i got "sorry. no data so far"

### ISSUE THREAD

**Issue by halatef** [cabrerahector/wordpress-popular-posts#342]
**here's the short code**
[wpp range='last30days' stats_comments=1 order_by='comments']

**and here's the debug:**
Plugin Configuration

Performance Nag: Inactive

Log Limit: Yes, keep data for 180 days

Log Views From: Everyone

Data Caching: Yes, 1 minute

Data Sampling: Yes, with a rate of 100

External object cache: No

WPP_CACHE_VIEWS: No

System Info

PHP version: 8.0.24

PHP extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, json, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, litespeed, bcmath, dba, dom, enchant, fileinfo, gd, imap, intl, ldap, exif, mysqlnd, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, snmp, soap, sockets, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlwriter, xsl, zip

Database version: 5.7.39-log-cll-lve

InnoDB availability: YES

WordPress version: 6.1

Multisite: No

Active plugins: Akismet Anti-Spam 5.0.1, aThemes Blocks 1.0.7, aThemes Starter Sites 1.0.24, Blockspare 2.1.1, Elespare 1.1.5, Fonts Plugin | Google Fonts Typography 3.2.0, Ivory Search 5.4.8, Nextend Social Login 3.1.6, QuadMenu 2.3.2, Rating BestWebSoft 1.6, Ultimate Category Excluder 1.6, WordPress Popular Posts 6.0.5, WPForms Lite 1.7.7.2, WP Post Author 3.2.1

Theme: ChromeNews (3.4.9) by AF themes

**Comment by cabrerahector** [comment]
Hi @halatef,

Nothing really stands out from your Debug info so if you haven't already please check out the suggestions from this FAQ: [I'm getting "Sorry, no data so far", what's going on?](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#im-getting-sorry-no-data-so-far-whats-up-with-that).

Since you're sorting posts by comments count, check that your site has actually received comments within the Time Range you especified (last 30 days).

**Comment by halatef** [comment]
I already checked the FAQs and nothing helps, also i have comments within that time

**Comment by cabrerahector** [comment]
Alright, could you please share your site's URL so I can have a look?

**Comment by halatef** [comment]
it worked when i used range all, so range param is not working
i also have the limit param not working, it always display 3 posts

**Comment by cabrerahector** [comment]
Can you please share your site's URL? Also, how are you adding the shortcode to your site?

**Comment by halatef** [comment]
http://sts-eg.com/reviewer/


[wpp range='all'  stats_date=1  limit=5  stats_comments=1 stats_views=1 order_by='comments' thumbnail_width=136 thumbnail_height=136  wpp_start='<div>' wpp_end='</div>' post_html=' {thumb} <a href="{url}">{text_title}</a>       ']
