### ISSUE TITLE
Increase pageviews while accessing post from API

### ISSUE THREAD

**Issue by abaykan** [cabrerahector/wordpress-popular-posts#348]
I found that the flow to increase `pageviews` is by make a POST request when we access the post. But I want to increase `pageviews` count too when `/wp-json/wp/v2/posts/id` is being accessed, is this possible? Thanks.

cc: @justakazh

**Comment by hackstreet1337** [comment]
i have same issue too

**Comment by cabrerahector** [comment]
Hi @abaykan & @hackstreet1337,

`/wp-json/wp/v2/posts/id` doesn't provide a suitable action hook that we could use to update the views count of a particular post/page ID when you send a `GET` request to this particular endpoint, so no unfortunately that's not possible (at the time of writing at least.)

What you could do instead is send a `POST` request to `/wp-json/wordpress-popular-posts/v1/popular-posts` right after your initial `GET` request to `/wp-json/wp/v2/posts/id`. Your `POST` request to `/wp-json/wordpress-popular-posts/v1/popular-posts` needs to include the following parameters for it to work:

- `_wpnonce` - A valid WordPress nonce created via `wp_create_nonce('_wpnonce')`
- `wpp_id` - The post/page ID
- `sampling` - Whether [Data Sampling](https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance#data-sampling) is enabled or not (1 = enabled, 0 = disabled)
- `sampling_rate` - The [sampling rate](https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance#what-is-sample-rate-for)

**Comment by abaykan** [comment]
Understood. At first I thought that there is a feature to increase the `pageviews` counter if we access the `/wp-json/wp/v2/posts/id`. In this case I will use that option, thanks for your response.
