### ISSUE TITLE
Can't get embed videos/pictures to show

### ISSUE THREAD

**Issue by peq42** [cabrerahector/wordpress-popular-posts#351]
Can't get videos embed in the post(youtube) and pictures posted in the middle to show on the list

## Steps to reproduce it

1. Make a post
2. Gets popular and goes to the list
3. Doesn't show pictures or embed videos

## Expected behavior
Obvious

## Environment

- Plugin version: latest
- WordPress version: 6.1
- PHP version:  8
- Active plugins: none

**Comment by peq42** [comment]
Oh I'm sorry, thought it was supposed to show embed vids and pictures by default.

Any way U could do it tho?

**Comment by cabrerahector** [comment]
> Oh I'm sorry, thought it was supposed to show embed vids and pictures by default.

Where did you get that idea from? The plugin doesn't mention anywhere that it can show videos embeds. It's _possible_ if you're familiar with WordPress & PHP development in general (see [How can I use my own HTML markup with WordPress Popular Posts](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#how-can-i-use-my-own-html-markup-with-your-plugin)), however it's not a feature that the plugin offers out of the box. You'd need to code that in yourself and/or find someone to assist you with that.

As for pictures, yes, the plugin can show images related to each post, like [Featured Images](https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/) for example (see [How does WordPress Popular Posts pick my posts' thumbnails?](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#how-does-wordpress-popular-posts-pick-my-posts-thumbnails) for more details.)

For your popular posts list to show thumbnails you first need to enable and configure all the related thumbnails settings, like so for example:

![image](https://user-images.githubusercontent.com/3186556/212726474-d69f25c9-cfa0-44db-9597-62fb351feec0.png)

![image](https://user-images.githubusercontent.com/3186556/212728361-54f8f840-d23a-4258-90a0-2a3108f03c2d.png)

**Comment by peq42** [comment]
Is there any way to display the post as "full" instead of excerpt or summary? I've another plugin that lists the newest posts in a separate page that have all those 3 options and when using "full" it works fine

again sorry, I'm a bit new to this

**Comment by cabrerahector** [comment]
> Is there any way to display the post as "full" instead of excerpt or summary?

Yep, that's doable too. It's not a feature included with the plugin though but -as I suggested before- the plugin provides tools to customize the HTML markup of your popular posts so virtually anything you can think of is possible.

Have a look at the link I shared above to learn more about customizing your popular posts list and if you have any questions please feel free to ask.

**Comment by peq42** [comment]
I tried looking into the documentation but i'm honestly lost..

I tried adding the following code to functions.php

```
function wpp_parse_fullhtml_in_popular_posts($html, $post_id) {

    if ( false !== strpos($html, '{posthtml}') ) {
        
        

       

            $html = str_replace('{posthtml}', $post_html, $html);

            
        
    }

    return $html;

}
add_filter('wpp_parse_custom_content_tags', 'wpp_parse_fullhtml_in_popular_posts', 10, 2);
```

Then made post HTML Markup into this:
`
<li class="{current_class}"><div class="wpp-item-data">{title}</div><div class="taxonomies">{taxonomy}</div><div class="wpp-item-data">{posthtml}</div> </li>`

but now the post list is just, the title and that's it, its incorporating the HTML/page content

**Comment by cabrerahector** [comment]
Hi @peq42,

Sorry for the late reply. I've been busy these days.

About your code, well, it doesn't seem to do anything? The `$post_html` variable isn't defined anywhere, but then you're trying to use it with `str_replace()`? Is this your complete code?
