### ISSUE TITLE
Shortcode with date range attribute

### ISSUE THREAD

**Issue by Ani-Soft** [cabrerahector/wordpress-popular-posts#357]
Hi,

I wanted to know if i can pass date range in shortcode to get data for specific time period.

This date range thing already working in wp-admin but wanted to know if same can be used in front-end with shortcode

Something like [wpp range="custom" daterange="yyyy-mm-dd,yyyy-mm-dd"]

TIA

**Comment by cabrerahector** [comment]
Hi @Ani-Soft!

No, there's no such feature unfortunately. The thing you see on the Stats screen is actually custom database queries especifically written for this screen.

If you want to get popular posts within a given time period you'd need to do the same (write custom database queries).
