### ISSUE TITLE
Thumbnail Size Issue, Blurry Image?

### ISSUE THREAD

**Issue by mossifer** [cabrerahector/wordpress-popular-posts#367]
I set the thumbnail size to 272x182 (a size from the theme), but it's displaying fuzzy.

How do I for sure get that particular thumb?

**Comment by cabrerahector** [comment]
Hi @mossifer,

Well, that depends. If the original image isn't big enough then the plugin can't do much about that.

Do you have a link you can share so I can have a look at it?

**Comment by cabrerahector** [comment]
Closed in favor to https://wordpress.org/support/topic/thumbnail-size-w-shortcode/
