### ISSUE TITLE
Is it possible to filter the posts based on a custom field?

### ISSUE THREAD

**Issue by sbikosfp** [cabrerahector/wordpress-popular-posts#369]
Is it possible to filter the posts in the wpp filter based on a boolean custom field? For example if a field is false in the post do not show it in the wpp shortcode list.

**Comment by cabrerahector** [comment]
Hi @sbikosfp,

The plugin doesn't provide such functionality so no it's not possible at this time.

If you're familiar with database queries in general you may be able to filter posts by custom field value via the various filter hooks available on [\WordPressPopularPosts\Query](https://github.com/cabrerahector/wordpress-popular-posts/blob/master/src/Query.php) though.
