### ISSUE TITLE
Order by date

### ISSUE THREAD

**Issue by JohnTFM** [cabrerahector/wordpress-popular-posts#379]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you’d like
I would like to be able to sort by date. Currently, I can only sort by comments, views, or avg. Use case: Sort by recent items, list the oldest items.
I believe this would be easy to implement and useful for all users.

**Comment by cabrerahector** [comment]
Hi @JohnTFM,

You may want to give [Recently](https://wordpress.org/plugins/recently/) a try. It's similar WordPress Popular Posts feature wise but it lists recent posts instead of most viewed/commented ones.
