### ISSUE TITLE
How to add attribute "theme" in shortcode wpp

### ISSUE THREAD

**Issue by pojoksoft** [cabrerahector/wordpress-popular-posts#382]
hi

i want to add theme "TIles" in shortcode. I try this but not working

[wpp header='Popular Posts' range='all' limit=5 stats_views=1 order_by='views' thumbnail_width=320 thumbnail_height=160 taxonomy=\'category\' theme='tiles']

and for HTML markup in "Before / after title" & "Before / after Popular Posts" I also couldn't find a way to add the shortcode

thank you

**Comment by cabrerahector** [comment]
Hi @pojoksoft,

The shortcode doesn't have a `theme` parameter as using themes with it isn't technically possible - at least not in the same way as you could with, for example, the WPP block or the classic widget.

To replicate the "Tiles" theme with the shortcode you would need to use the following parameters (in addition to the ones you already have):

- **_stats_category_** - to have the shortcode display the post category
- **_header_start_** and **_header_end_** would be equivalents to "Before / after title"
- **_wpp_start_** and **_wpp_end_** would be equivalents to "Before / after Popular Posts"
- **_post_html_** - the actual HTML markup of each post

So your shortcode would look something like this now:

```
[wpp header_start='<h2 class="widgettitle">' header='Popular Posts' header_end='</h2>' range='all' limit=5 thumbnail_width=320 thumbnail_height=160 stats_category=1 wpp_start='<ul class"wpp-list wpp-tiles">' post_html='<li class="{current_class}">{thumb}<div class="wpp-post-data">{taxonomy} {title}</div></li>' wpp_end='</ul>']
```

That would take care of the HTML side of things.

You also need to add [Tiles' CSS rules](https://raw.githubusercontent.com/cabrerahector/wordpress-popular-posts/master/assets/themes/tiles/style.css) to your theme as well, either via **Appearance > Customize > Additional CSS** or by adding these CSS rules to your theme's stylesheet.
