### ISSUE TITLE
Rest API get 404

### ISSUE THREAD

**Issue by MatrixYe23** [cabrerahector/wordpress-popular-posts#392]
## Describe the problem
I have install wordpress-popular-posts, and active.
and use as block html as below: 
`[wpp range='last30days' stats_comments=1 order_by='comments']`

and publish 

## Steps to reproduce it
when i open my wordpress, 
the rest api '/index.php?rest_route=/wordpress-popular-posts/v2/widget?is_single=0&lang=0'  return 404 as below
![image](https://github.com/user-attachments/assets/a6e9eac1-ff2f-4a02-96d8-9f2a69f4a24f)
the the block html show as:
![image](https://github.com/user-attachments/assets/fc23083f-c084-48eb-a962-44a19dd49456)

## Expected behavior

![image](https://github.com/user-attachments/assets/bf04d598-dabc-4c51-9a2f-1083e9af6195)

## Environment

- Plugin version:  7.0.1
- WordPress version: 6.5.5
- PHP version: 8.3.9
- Active plugins: Hello Dolly

**Comment by cabrerahector** [comment]
Hi @MatrixYe23,

Make sure that you're using a Permalink structure that's not the `Plain` one, or else REST API endpoint will not work.

**Comment by MatrixYe23** [comment]
Hi @cabrerahector,

it works after not use the Plain Permalink structure. Thanks!
