### ISSUE TITLE
Allow selecting custom user access levels when logging views

### ISSUE THREAD

**Issue by cabrerahector** [cabrerahector/wordpress-popular-posts#4]
Let the user decide what views to log in a more granular way (eg. Log views from Subscribers only).

**Comment by ste93cry** [comment]
:+1:

**Comment by espellcaste** [comment]
+1

**Comment by nawin2019** [comment]
111

**Comment by cabrerahector** [comment]
Unlikely to happen, @nawin2019. I looked into this some time ago and there's currently no way to implement this feature in a reliable way due to the way WordPress handles roles & capabilities (especially on WordPress Multisite, which WPP supports.)

The reason I haven't closed this issue yet is mainly me hoping that WordPress will improve how it handles user roles / capabilities in a future release. Although seeing now that it's been over 7 years since this issue was first created maybe it's time to let this one go. I'll give this some thought.

**Comment by nawin2019** [comment]
Ok
