### ISSUE TITLE
Offset Parameter for Pagination

### ISSUE THREAD

**Issue by richvida** [cabrerahector/wordpress-popular-posts#47]
Hi Hector,

It would be nice to have the ability to offset the query so the popular posts can be paginated.

Have you ever considered enhancing WPP to support it?

http://codex.wordpress.org/Class_Reference/WP_Query#Pagination_Parameters

**Comment by cabrerahector** [comment]
For any future reader: this was implemented with WPP 4.0.0, check the WPP_Query class for details.
