### ISSUE TITLE
Problem with the database

### ISSUE THREAD

**Issue by byron222** [cabrerahector/wordpress-popular-posts#55]
"Sorry. No data so far." always display.
I notice that the wp_popularpostsdata in my database receive nothing.
im using ajax to send my data to the database.
how and what is the problem?

**Comment by ochoarobert1** [comment]
I have the exact issue, i don't know why my database remains empty. 
i've put the popularposts to see my post_type: post  and nothing happened.

![captura de pantalla 2015-01-07 a la s 9 47 38 am](https://cloud.githubusercontent.com/assets/4027931/5646741/920118c2-9651-11e4-850c-0d8e9313a9f4.png)

**Comment by ochoarobert1** [comment]
i've solved it so easily 

i forgot to put the <?php wp_head(); ?> in my head section :3 
@byron222 you should check this

**Comment by byron222** [comment]
@cabrerahector  my site's URL is not for public now, so can we take contact in private or personal?

**Comment by byron222** [comment]
@ochoarobert1  Thank you! I'll try!

**Comment by byron222** [comment]
by the way, alguien habla español?

**Comment by ochoarobert1** [comment]
Yo hablo español

**Comment by cabrerahector** [comment]
Venezolano por acá, pero prefiero dar soporte en inglés para que la información alcance al mayor número de personas posible.

@byron222 assuming you've already checked [this](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#im-getting-sorry-no-data-so-far-whats-up-with-that), take a look at your browser's developer console and look for Javascript errors.

And:

> If you're having problems with WPP, my first suggestion would be try disabling all other plugins and then re-enable each one to make sure there are no conflicts. Also, try switching to a different theme and see if the issue persists.

**Comment by byron222** [comment]
@ochoarobert1 Mucho gusto Ochoa.
Y muchas gracias por la información!!

**Comment by byron222** [comment]
@cabrerahector  Mucho gusto Hector.
Si tienes razón, en inglés mejor.

OK!
I'll check my site.

**Comment by cabrerahector** [comment]
Since the OP hasn't replied in over a month, I'll assume he managed to fix things on his end and so I'm closing this issue.

Byron, if you need further help please let me know.
