### ISSUE TITLE
Count by IP

### ISSUE THREAD

**Issue by coldpumpkin** [cabrerahector/wordpress-popular-posts#57]
Is it possible that the view counter is based by IP and not by everytime the page loads? Perhaps also give it a timer, so that we can choose the interval from when it should log the IP or not. So if it was set for 10 minutes, the same IP wouldn't count as a view in the same post more than once.

**Comment by cabrerahector** [comment]
Hi there,

A similar issue has been discussed previously [here](https://github.com/cabrerahector/wordpress-popular-posts/issues/44). Chances are I won't be implementing this in the near future, but I might add a custom action as someone suggested in that discussion so people can override the update views process.

Anyways, please keep an eye on that topic for more :)
