### ISSUE TITLE
Add support for custom taxonomies

### ISSUE THREAD

**Issue by cabrerahector** [cabrerahector/wordpress-popular-posts#68]
Currently, WPP only supports custom post types. It'd be a nice addition to have it support custom taxonomies as well.

I'm creating this issue so I don't forget about it. Will post back here once I start working on this.

**Comment by ronilaukkarinen** [comment]
:+1: Much needed here.

**Comment by byron222** [comment]
i need this too!

**Comment by ronilaukkarinen** [comment]
FYI, we were tired of waiting, so wrote our own plugin. You can get the plugin [here](https://github.com/digitoimistodude/dude-most-read-posts). Strongly dev oriented though.

**Comment by cabrerahector** [comment]
@byron222 @ronilaukkarinen if you check the wpp4 branch you'll notice the code for this is already there, just needs the "front-end" counterpart to be updated to reflect this change :)

**Comment by byron222** [comment]
how can i use the custom taxonomy?

i download the wpp4!

**Comment by byron222** [comment]
i try this

`<div class="content">
                       
       
              <?php 
		

			
				$args = array(
    			'range' => 'last30days',
    			'limit' => 4,
				'thumbnail_width' => 30,
    			'thumbnail_height' => 30,
				'order_by' => 'views',
    			'post_type' => 'office',
				'tax_query' => array(
                    array(
                        'taxonomy' => 'area',
                        'field' => 'slug',
                        'terms' => 'tokyo',
                        ),
                    )
				);
				$popular = new WPP_query( $args );
				$wpp = $popular->get_posts();
				//var_dump( $popular->get_posts() );
				foreach ( $wpp as $wppfield ) :
				
				$id = $wppfield->id;
				
				$title = $wppfield->title;
				$url = get_permalink( $id );
				$catch_field = get_field( "catch", $id );
				$image_url = wp_get_attachment_image_src(get_post_thumbnail_id($id), 'medium');
				$image = '<img src="'.$image_url[0].'" / >';
		
		
                  ?>
              	<div class="Top-rank_wrapp">
              	    <div class="thumb">
              	          <a href="<?php echo $url; ?>" title="<?php echo $title; ?>" class="featured-thumbnail featured-thumbnail-big">
              	              <?php echo $image; ?>
              	          </a>
              	    </div>
              	    <div class="text">
              	      <p class="catch"><a href="<?php echo $url; ?>" data-list-id="<?php $id; ?>"><?php echo $catch_field; ?></a></p>
              	      <p class="views"><?php echo wpp_get_views( $id, 'all' ); ?><span>views</span></p>
              	      <p class="title"> <a href="<?php echo $url; ?>" data-list-id="<?php echo $id; ?>"><?php echo $title; ?></a></p>
              	    </div>
              	</div>

              <?php endforeach; wp_reset_postdata();
		 ?>

    </div>`

**Comment by byron222** [comment]
or try this

`<?php $args = array(
              'post_type' => 'office',
              'posts_per_page' => 4,
              'orderby' => 'meta_value_num',
              'meta_key' => 'views',
              'tax_query' => array(
                    array(
                        'taxonomy' => 'area',
                        'field' => 'slug',
                        'terms' => $area,
                        ),
                    ),
           );
                  $postslist = get_posts( $args );
                  foreach ( $postslist as $post ) :
                    setup_postdata( $post ); ?>

              <div class="Top-rank_wrapp">
                  <div class="thumb">
                        <a href="<?php the_permalink() ?>" title="<?php the_title_attribute(); ?>" class="featured-thumbnail featured-thumbnail-big">
                            <?php the_post_thumbnail( 'mediam', array( 'class' => 'crop_image' )); ?>
                        </a>
                  </div>
                  <div class="text">
                    <p class="catch"><a href="<?php the_permalink(); ?>" data-list-id="<?php the_ID(); ?>"><?php $catch_name = get_field('catch'); echo $catch_name; ?></a></p>
                    <p class="views"><?php echo wpp_get_views( $id, 'all' ); ?><span>views</span></p>
                    <p class="title"><a href="<?php the_permalink(); ?>" data-list-id="<?php the_ID(); ?>"><?php the_title(); ?></a></p>
                  </div>
              </div>


              <?php endforeach; wp_reset_postdata(); ?>`

**Comment by cabrerahector** [comment]
@byron222 try this:

```php
$args = array(
    'post_type' => 'office',
    'limit' => 4,
    'range' => 'last30days',
    'order_by' => 'views',
    'taxonomy' => 'area',
    'term_id' => '1,3,4' // CHANGE THIS TO YOUR TERM IDS, COMMA SEPARATED
);
$popular_posts = new WPP_query();

echo "<pre>";
var_dump( $popular_posts->get_posts() );
echo "</pre>";
```
