### ISSUE TITLE
Add ability to set a custom Time Range

### ISSUE THREAD

**Issue by cabrerahector** [cabrerahector/wordpress-popular-posts#70]
As said on the title.

**Comment by andrejm** [comment]
This seems to be the one and only feature I'm missing in this plugin - I specifically need to show most popular posts from last 3 days :)

**Comment by cabrerahector** [comment]
It's one of the features people have requested the most during all these
years, actually. I too want it for myself :P

There are still a few things that need to be done before it can happen,
though.

**Comment by andrejm** [comment]
Understood. Keep my fingers crossed :) The plugin looks like solid piece of work.

**Comment by espellcaste** [comment]
Off-topic: I agree about @andrejm comment! I was scared of using it at first, but after looking at the code and the docs looks solid. Congrats on the work. =)

**Comment by codescribblr** [comment]
+1 for custom date ranges. I need 3 and 5 days, so I've had to add those in as options in the switch statements. :(
