### ISSUE TITLE
Posts not displaying when using different domain for front-end

### ISSUE THREAD

**Issue by whackdesign** [cabrerahector/wordpress-popular-posts#71]
I've setup my site with the live domain, but the backend of the site lives under a different url. I believe this is causing a problem with the plugin, have you had to deal with this in the past? Any help would be greatly appreciated.

**Comment by cabrerahector** [comment]
Hi there!

What kind of issue are we talking about here? You didn't mention it. Also, sharing your site's URL would be of help.

**Comment by whackdesign** [comment]
The site is http://www.seismic.com/blog. The popular posts aren't displaying on the blog. What I was saying before is that the site lives under http://www.seismic.com and the admin area lives under http://seismicweb.azurewebsites.net/wp-admin, so I'm assuming that might be creating an issue with the plugin. Have you dealt with this type of issue before?

**Comment by cabrerahector** [comment]
Indeed. Any [AJAX](http://codex.wordpress.org/AJAX) based script (including WPP) will fail to work on your site because cross domain requests are automatically blocked by most (if not all) web browsers for security reasons - unless the domain is specifically configured to allow it.

To solve it, please [try this](http://stackoverflow.com/a/13174880 ) and post back the results.

**Comment by whackdesign** [comment]
I see, not this is a windows server so I have to use the the web.config file instead of the .htaccess, any idea as to how I can set that up?

**Comment by cabrerahector** [comment]
[This](http://encosia.com/using-cors-to-access-asp-net-services-across-domains/) may be what you need.

**Comment by whackdesign** [comment]
So this is what my code looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<system.webServer>
		<httpProtocol>
	    	<customHeaders>
				<add name="Access-Control-Allow-Origin" value="*" />
				<add name="Access-Control-Allow-Headers" value="Content-Type" />
		   </customHeaders>
		</httpProtocol>
		<staticContent>
	    	<mimeMap fileExtension=".woff" mimeType="font/woff" />
		</staticContent>
	    <rewrite>
	    	<rules>
				<rule name="wordpress" patternSyntax="Wildcard">
					<match url="*"/>
						<conditions>
							<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true"/>
							<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true"/>
						</conditions>
					<action type="Rewrite" url="index.php"/>
				</rule></rules>
	    </rewrite>
	</system.webServer>
</configuration>
```
It still doesn't seem to work... Any other ideas? Thanks for your help.

**Comment by whackdesign** [comment]
Here is what my console says:
![screen shot 2015-03-13 at 12 07 24 pm](https://cloud.githubusercontent.com/assets/130901/6645408/9df79380-c979-11e4-8e16-79537505e1f7.png)

**Comment by cabrerahector** [comment]
[Check this](http://stackoverflow.com/questions/12458444/enabling-cross-origin-resource-sharing-on-iis7), sounds quite similar to what you're experiencing over there.

**Comment by cabrerahector** [comment]
Since there has been no further replies from the OP (and that this is a server side problem), I'm closing this issue.
