### ISSUE TITLE
Custom category function instead of category content tag

### ISSUE THREAD

**Issue by shivika** [cabrerahector/wordpress-popular-posts#72]
Hi,

I am using your plugin with template tags and have a custom category function that I use to call only parent categories of assigned subcategories for each post (client only selects subcategories).  I'm wondering if there's an easy way to replace {category} with my custom category function php call. 

Thanks!

**Comment by cabrerahector** [comment]
Hi @shivika,

There's no way to change the {category} tag directly. However, you can use the [wpp_custom_html filter](https://github.com/cabrerahector/wordpress-popular-posts/wiki/3.-Filters#wpp_custom_html) to use your own category function.

**Comment by cabrerahector** [comment]
We continued the conversation at [WordPress.org | Custom category function instead of {category}](https://wordpress.org/support/topic/custom-category-function-instead-of-category).
