### ISSUE TITLE
Displays popular pages but not posts?

### ISSUE THREAD

**Issue by PixelRelish** [cabrerahector/wordpress-popular-posts#73]
I've scanned the Support forum for hours and not found the answer, so asking herein:  Installed the plugin on a FoundationPress-based custom site using your recommended inline code because I want the information called up within the main body of the page, not a sidebar.  Here is the code:

                <div class="row padTtwo">
                    <div class="medium-9 end columns">
                    	<?php wpp_get_mostpopular( 'post_type="post" excerpt_format=1&excerpt_length=400&post_html="<li>{thumb} {title} {summary}</li>"' ); ?>
                        <h6>read on <em class="fa fa-arrow-circle-right"></em></h6>
                    </div>
                </div>

If I have it pull up "post, page" then the page info does come up and does take on the custom styling I've created in my css.  But nothing if I limit, as above, to only posts, which is what I want.

I am still working on my localhost and so cannot send a URL (can upload the site, though, if no way for you to answer without examining the pages).

Both posts and pages use the same header.php file, so that's not the issue.  Both, too, would access the same admin folder, right, so that's not the issue.  Have the plugin set to base on views, not comments, but even put in some dummy comments (available on posts pages only) just in case that is the issue.

Any ideas?

**Comment by cabrerahector** [comment]
Hi there!

You have a minor error on your code: there's a space after `post_type="post"`

`            <div class="row padTtwo">
                <div class="medium-9 end columns">
                    <?php wpp_get_mostpopular( 'post_type="post"&excerpt_format=1&excerpt_length=400&post_html="<li>{thumb} {title} {summary}</li>"' ); ?>
                    <h6>read on <em class="fa fa-arrow-circle-right"></em></h6>
                </div>
            </div>`

**Comment by PixelRelish** [comment]
OK, now I feel extremely stupid.  Thank you for your help!!!

**Comment by cabrerahector** [comment]
Don't worry about it. We all have moments like that :P

**Comment by PixelRelish** [comment]
Curious as to why, even with the mistake, the code DID pull up the page, though, just not posts?

**Comment by PixelRelish** [comment]
Hmm, same error (just copied and pasted in your code)

**Comment by PixelRelish** [comment]
In case it helps, here is the template page's complete code.  I am in the process of finishing changing as many elements as possible from straight html into WordPress-enabled elements to make as many things as possible edited by the client, who does not read much html.

<?php /*
Template Name: Site Home 
*/
get_header(); ?>

    <header class="row bgwhite">
      <div class="small-12 columns">
      	<div class="row">
        	<div class="hero">
            	<span id="headimg1" role="img" aria-label="Krishanti">
                    	<span class="inner"></span>
                    </span>
            </div>
        	<div class="small-8 small-offset-4 columns hdwords opacEight">
                <div class="row">
                	<div class="small-11 small-offset-1 columns">
                    	<h4>you are</h4>
                    </div>
                </div>
                <div class="row">
                	<div class="small-12 columns">
                    	<h1>LIMITLESS</h1>
                    </div>
                </div>
                <div class="row">
                	<div class="small-10 small-offset-2 medium-9 medium-offset-3 columns">
                    	<h5>Activate the Power of Your Spirit<br class="hide-for-small-down" />
                        and Create the Life of Your Dreams</h5>
                    </div>
                </div>
            </div>
        </div>
      </div>
  </header>
  
  <?php get_template_part( 'obar' ); ?>

  
  <section class="row bodyfont bgwhite">
      <div class="small-12 columns">
      
      	
        <div class="row">
        	<div class="large-6 columns padTone">
	    		<h1 class="margTtwo margBzero">WHAT'S MISSING...</h1>
                <p class="lead">Happiness<span class="punct">?</span>  Love<span class="punct">?</span>  Fulfillment<span class="punct">?</span>  Purpose<span class="punct">?</span></p>
                <p class="lead">Don't wait:  Start living the life of your dreams today!  I've helped thousands transform their lives.  I can help you, too.</p>
            </div>
            <div class="large-6 columns padTtwo ads">
            	<ul class="small-block-grid-1 medium-block-grid-2">
                	<li><a href="#" class="medium alert button radius bgpowers"><h2 class="margBzero"><span class="bump">Activate Your</span></h2><h5 class="margTzero"><span class="bump">Psychic Super Powers</span></h5></a></li>
                    <li><a href="#" class="medium alert button radius bgoffm"><h2 class="margBzero"><span class="bump">Get Him</span></h2><h5 class="margTzero"><span class="bump">Off Your Mind</span></h5></a></li>
                    <li><a href="#" class="medium alert button radius bgmoney"><h5 class="margBzero"><span class="bump">Manifest Money</span></h5><h2 class="margTzero"><span class="bump">Now</span></h2></a></li>
                    <li><a href="#" class="medium alert button radius bgdevel"><h5 class="margBzero"><span class="bump">Intuitive Development</span></h5><h2 class="margTzero"><span class="bump">Training</span></h2></a></li>
                </ul>
            </div>
          </div>
      
      	
        <div class="row bodyfont">
        	<div class="medium-9 columns padTone">
                <div class="row">
                    <div class="medium-7 medium-push-5 columns">
                    	
                        <?php $the_query = new WP_Query( 'showposts=1' ); ?>
                        <?php while ($the_query -> have_posts()) : $the_query -> the_post(); ?>
                        <h2><a href="<?php the_permalink() ?>"><?php the_title(); ?></a></h2>
                        <p><?php echo substr(strip_tags($post->post_content), 0, 400);?>...</p>
                        <h6>read on <em class="fa fa-arrow-circle-right"></em></h6>
                        <?php endwhile;?>
                    </div>
                    <div class="medium-5 medium-pull-7 columns padTone">
                        <img src="http://localhost:81/wp-content/uploads/2015/03/ph_place1.jpg" alt="placeholder"/>
                    </div>
                </div>
                
                <div class="row padTtwo">
                    <div class="medium-9 end columns">
                    	<?php wpp_get_mostpopular( 'post_type="post"&excerpt_format=1&excerpt_length=400&post_html="<li>{thumb} {title} {summary}</li>"' ); ?>
                        <h6>read on <em class="fa fa-arrow-circle-right"></em></h6>
                        
                    </div>
                </div>
            </div>
            
            <div class="medium-3 columns padTtwo">
            	<h5 class="margBzero">Recent Posts</h5>
                <ul class="posts">
                	<?php $the_query = new WP_Query( 'showposts=6' ); ?>
                    <?php while ($the_query -> have_posts()) : $the_query -> the_post(); ?>
                    <li class="pitem"><a href="<?php the_permalink() ?>"><?php the_title(); ?></a><br />
                    <?php echo substr(strip_tags($post->post_content), 0, 48);?>...</li>
                    <?php endwhile;?>
                </ul>
            </div>
        </div>
    
  </div>
  </section>
 
<?php get_footer(); ?>

**Comment by cabrerahector** [comment]
Just tested your template on my localhost (I'm actually working on the plugin now) and WPP lists posts only.

Let's start from the beginning and build from there:

```
<?php
    if ( function_exists('wpp_get_mostpopular') )
        wpp_get_mostpopular( 'range="all"&post_type="post"' );
?>
```

**Comment by PixelRelish** [comment]
OK, I pasted your "Let's  start from here..." code into the page (in place of what I had previously).  Same error message.

**Comment by cabrerahector** [comment]
That's odd. You'll have to upload your dev site somewhere so I can take a look. I'll be online for a while, so take your time. Let me know when you're done, alright?

**Comment by PixelRelish** [comment]
OK.  Thank you!  Will likely take me a few hours, because I'm in the middle of editing some other pages and don't want to lose my place :-)
