### ISSUE TITLE
I installed WPP, but nothing is loading on the home page.

### ISSUE THREAD

**Issue by stuartweir** [cabrerahector/wordpress-popular-posts#76]
I have added:

    <?php
        if (function_exists('wpp_get_mostpopular'))
        wpp_get_mostpopular();
    ?>

to my header.php file, but it does not seem to load the most popular pages (in fact, it doesn't show anything at all). What am I doing wrong?

Also, I've checked, and
    
    <?php wp_head(); ?> 

is in the header.php file. Do I have to specify certain tags, and if so, how would I accomplish that?

**Comment by cabrerahector** [comment]
Hi Stu!

Question: why are you adding the wpp_get_mostpopular() template tag to your theme's header.php?

**Comment by stuartweir** [comment]
Hi Hector!

I thought that was the manual way of adding it to the site. If I try to go to the Home "page" in the admin dashboard of WordPress, it doesn't give me the option to add it. If I go to Appearance -> Widgets, I only have access to drag WPP into a Footer...not the header or even the home page. So I'm somewhat confused as to what I should do.

**Comment by cabrerahector** [comment]
> I thought that was the manual way of adding it to the site.

The `wpp_get_mostpopular()` template tag allows you to add the listing anywhere on your page, indeed. It can be placed anywhere between the `<body>` and `</body>` HTML tags.

> If I go to Appearance -> Widgets, I only have access to drag WPP into a Footer...not the header or even the home page. So I'm somewhat confused as to what I should do.

Ah, that's because your current theme only allow widgets on your footer section. If you want to show the listing somewhere else than the footer, then the `wpp_get_mostpopular()` template tag is what you need :)

Unfortunately, I can't Skype right now since I'm at work. If you share your site's URL, I may be able to give you further instructions.

**Comment by stuartweir** [comment]
Thanks, that was a lot of help!

So, it's now showing up on the homepage, but says "Sorry, no data so far." Does this mean I have to set it up in the dashboard still to search for specific tags, etc?

**Comment by cabrerahector** [comment]
Nope, that means the plugin seems to be working correctly :)

Check [here](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#why-wordpress-popular-posts)  and [here](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#how-does-the-plugin-count-views--calculate-the-popularity-of-posts) for more detailed info on WPP works.

Let me know if you need further help with the plugin, alright? I'll be online for around half an hour before I go home.

**Comment by stuartweir** [comment]
Thanks so much, you've been so helpful. Will do, I'm about to go home myself so you might here from me tomorrow :)

**Comment by stuartweir** [comment]
So I managed to figure everything out. Thank you once again for your help :)
