### ISSUE TITLE
die() in update_views_ajax() is way too aggressive

### ISSUE THREAD

**Issue by pippinsplugins** [cabrerahector/wordpress-popular-posts#78]
This check is far too aggressive: https://github.com/cabrerahector/wordpress-popular-posts/blob/master/wordpress-popular-posts.php#L1262

It's causing ajax requests from other plugins to fail as well. Anytime there is an `id` key in `$_POST` that is not numeric, it will kill the request.

There must be a check as well to ensure only ajax requests from this plugin get killed.

**Comment by cabrerahector** [comment]
Hi there!

There's a nonce check in place for that reason. Could you please tell me which plugins are affected by this so I can check?

**Comment by pippinsplugins** [comment]
You're using an `II` statement, so it dies if the nonce doesn't verify OR the `id` key is non numeric.
```php
if ( !wp_verify_nonce($_POST['token'], 'wpp-token') || !$this->__is_numeric($_POST['id']) )
```

**Comment by cabrerahector** [comment]
Yes, thanks. I updated my previous reply after realizing what the problem is.

**Comment by haydenjames** [comment]
same issues here. update_views_ajax.

I have ajaxify disabled but still gftmetrix shows this single plugin calling admin-ajax.php every page view.

**Comment by cabrerahector** [comment]
What the OP reported has no relation to what you're describing, @haydenjames. It was an entirely different issue resolved long ago now.

There's another AJAX script that WPP runs to track the views count of your posts and pages and it runs every time someone visits your posts / pages. Unlike the _Ajaxify widget_ feature, this Ajax call can't be disabled for obvious reasons :P

If you're running a high-traffic site, or simply want to reduce the number of calls WPP makes to update the views count of your posts / pages, then (please read here)[https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance#data-sampling].
