### ISSUE TITLE
Hide WPP if there's no data

### ISSUE THREAD

**Issue by richvida** [cabrerahector/wordpress-popular-posts#79]
If there something I can add to my if statement that will hide WPP when it doesn't have any data?

    <?php if ( function_exists ( 'wpp_get_mostpopular' ) ) : ?>

        <div class="posts popular">

            <?php wpp_get_mostpopular ( array( 'order_by' => 'views', 'range' => 'weekly', 'post_type' => 'post', 'limit' => 10, 'pid' => get_the_ID() ) ); ?>

        </div>

    <?php endif; ?>

I know I could edit the plugin code directly to remove the text, but that's not exactly a scalable solution.

**Comment by cabrerahector** [comment]
Hi there!

Unfortunately, no. It happens to be the one of the few HTML outputs that can't be changed from outside the plugin.

On a side note, recently I stumbled upon [this](http://philsmart.me/wordpress-popular-posts-plugin-raw-data-array/ "Hacking the WordPress Popular Posts Plugin for a Raw Data Array") and while I know it's not the answer you're looking for it gives you full control over the output. Don't know if it helps, but I thought I'd share it anyways.

**Comment by richvida** [comment]
Yo!

Maybe changing the output is the wrong way to go about this. 

What do you think about adding a class to the output in a future release? That would allow it to be hidden just using CSS -- a much easier solution!

**Comment by cabrerahector** [comment]
Alright, sounds good to me. Thanks for the suggestion :)
