### ISSUE TITLE
How to use plugin API?

### ISSUE THREAD

**Issue by basememara** [cabrerahector/wordpress-popular-posts#80]
I'd like to expose popular posts through a web service and would like to use this plugin's API, but I can't seem to do this.. everything seems to marked as private. And `wpp_get_mostpopular` returns the actual HTML instead of the data.

For example, with the WP-Postviews plugin, I can do this:
```
$the_query = new WP_Query(array(
        'posts_per_page' => '5',
        'v_sortby' => 'views', 
        'post_type' => array( 'post', 'music', 'videos', 'albums' ))
     );
```
Is this possible with Wordpress Popular Posts plugin?

**Comment by cabrerahector** [comment]
Hi there!

Indeed, most of the methods are either protected or private so unfortunately you can't access them directly. At least, not for the time being. I'll consider changing that in a future version.

For the time being, here's an interesting workaround by Phil Smart that might come in handy: http://philsmart.me/wordpress-popular-posts-plugin-raw-data-array/

**Comment by cabrerahector** [comment]
In case you want to use the WP_Query class:

- https://wordpress.org/support/topic/access-by-url-httpexamplcat702sort_bymost_popular?replies=16#post-6216261

**Comment by cabrerahector** [comment]
Alternatively, you could try extending WPP's class. That'd give you access to the `_query_post` method, which is _protected_.

**Comment by cabrerahector** [comment]
... and there's also [this](https://wordpress.org/support/topic/generic-post-sorting-using-post-views) and [this](https://wordpress.org/support/topic/generic-post-sorting-using-post-views?replies=15#post-6826813).

(Sorry for the bunch of comments, I just keep remembering stuff hehe)

**Comment by basememara** [comment]
Cool, thx for all those suggestions! Phil Smart's hack about filtering the data out before it gets to the `wpp_get_mostpopular()` doesn't seem so invasive since it's not changing any data or structures. But I really like the last post you sent because having the views as a custom field of the posts just opens up so many doors.

I have another suggestion to keep on this thread :)
```
global $wpdb;
$sql = "SELECT postid, pageviews, last_viewed FROM {$wpdb->prefix}popularpostsdata ORDER BY pageviews DESC";
return $wpdb -> get_results($sql);
```
This simply returns the post ID and views count. This is what I went with in my scenario because I exposed this as a web service since I'm updating a mobile app's internal database of WordPress posts (for offline viewing).

For your consideration, perhaps something that would resolve all these suggested implementations would be to expose a public function called `query_posts` that would wrap the protected `_query_posts` function. The function parameter would have to simplified though instead of passing the instance, maybe like this?:
```
protected function _query_posts($range, $post_type, $cat, $order_by, $limit) {
  global $wpdb;
  
  // merge parameter values
  $instance = $this->__merge_array_r(
    $this->defaults,
    array(
      'limit' => $limit,
      'range' => $range,
      'cat' => $cat,
      'order_by' => $order_by,
      'post_type' => $post_type
  );

  return $this->_query_posts($instance)
}
```
Thanks anyway for an awesome solid plugin!! And for the help too!!

**Comment by cabrerahector** [comment]
> I really like the last post you sent because having the views as a custom field of the posts just opens up so many doors.

Indeed. That's why I fixed that thread on the top of the support forum, I guessed some people might give it a good use.

What I don't like about that approach is that you can't run more complex queries, such as "get me the most viewed posts today" unless you create a custom field per time range, and then you'd need to keep updating it, etc.

> For your consideration, perhaps something that would resolve all these suggested implementations would be to expose a public function called query_posts that would wrap the protected _query_posts function.

Thing is that limiting the parameters to just these (the ones you posted) will make people say "please, add this one too!" (the happy problem of having a plugin with so many options hehe) and since WPP does have quite a few of them the parameter list of such a function would end up being insanely huge.

I might just go for something like this instead:

```php
public function query_posts( $args = array() ) {
  global $wpdb;

  // merge parameter values
  $instance = $this->__merge_array_r(
    $this->defaults,
    $args
  );

  return $this->_query_posts($instance)
}
```
Much simpler, I believe. Just pass whatever options you need using an array and let WPP do the rest.

I'll think about it.

> Thanks anyway for an awesome solid plugin!! And for the help too!!

Thank _you_ for the nice words :)
