### ISSUE TITLE
Automatically Detect Categories to Include

### ISSUE THREAD

**Issue by PromInc** [cabrerahector/wordpress-popular-posts#85]
Love this plugin - very handy.

My site have very diverse topics, and therefor in a sidebar widget I don't want to show ALL of the top posts across the site because they may not be relevant to the post the visitor is currently viewing.  The solution would be to be able to select the top posts that correlate to the categories that a given post is listed in.

While you offer the ability to specify categories to include, this needs to be done dynamically - not hard set.

I have modified your plugin to make it work for my needs - however I feel this is a valuable feature and look forward to any potential updates that may come along.  For those reasons, I'm offering what solution I implemented to you to use and integrate into your plugin as you see fit.  Admittedly, my solution is a bit more of a **_hack**_ than a perfect solution for your plugin - but the concept is there.

I replaced line 1551 of `wordpress-popular-posts.php` with the following code:

```
if( $instance['cat'] == 999999 ) {
    $cat_ids = array();
    foreach( get_the_category() as $activeCat ) {
        /* Get parent ID */
        if( $activeCat->parent == 0 ) {
            $useThisCat = $activeCat->cat_ID;
        } else {
            $useThisCat = $activeCat->parent;
        }
        $cat_ids[] = $useThisCat;  /* Add parent */
        foreach( get_categories( 'parent='.$useThisCat ) as $child ) {
            /* Add children */
            $cat_ids[] = $child->cat_ID;
        }
    }       
} else {
                $cat_ids = explode(",", $instance['cat']);
}
```

Now, if I enter in `999999` into the `Category(ies) ID(s):` field of the widget, the automatic category detection is triggered.  This of course would be better implemented via a checkbox or radio button, but for my quick **_hack**_ this suffices.  I then get the categories that the post is listed in (it works with multiple categories).  I loop through those categories to also get the categories parents followed by the parents children - thus ALL categories under the parent.  I then set all of those categories to your $cat_ids array and the rest of the plugin code kicks in as normal.

The end result is that a photography article is not being recommended as a top post for a woodworking article.  Instead woodworking gets more woodworking posts.

Again, thank you for a great plugin - I look forward to continuing to use it!

**Comment by cabrerahector** [comment]
I had a similar idea in mind, but with a different approach: when viewing a taxonomy archive page (category.php, tag.php, a-custom-taxonomy.php, etc), have WPP list the most popular entries of the taxonomy ([issue](https://github.com/cabrerahector/wordpress-popular-posts/issues/10)). Yours, on the other hand, works on single.php and lists posts from similar categories. It's a "related popular posts" hack. And a very interesting tweak, I must say!

I'm pretty sure other users would like to have this feature, so thanks for the contribution :) Now I need to find the best way to have my idea and yours coexist and be user-friendly as well hehe

**Comment by PromInc** [comment]
Exactly - glad you like the idea.

Here is a link to my blog if you are interested in seeing it in action at all.
http://promincproductions.com/blog
It's currently populating data - I just installed it this morning. I'll admit I don't get a ton of traffic, so it might take a while for it to be truly powerful.

One other small suggestion that in time really won't become a big deal, but regarding the (**no data** filter)[https://github.com/cabrerahector/wordpress-popular-posts/wiki/3.-Filters#wpp_no_data] you have implemented - that worked great!  One additional option that would have been nice here in my mind would be to hide the widget completely if no data was available.  I could set the text to "" via the filter, but there isn't a way to make the heading (widget-title) not display - is there?

Sorry - that probably shouldn't be crammed into this topic... just sharing the thoughts.  Thanks for the great plugin though!!!!  Saved me from the stress of developing one myself - which was my first thought for some reason.  ha!

**Comment by cabrerahector** [comment]
> One additional option that would have been nice here in my mind would be to hide the widget completely if no data was available

> Sorry - that probably shouldn't be crammed into this topic... just sharing the thoughts.

Don't worry. I don't mind the occasional off-topic chit-chat :)

Since you seem to like little hacks, here's a quick an' dirty one using the `wpp_no_data` filter:

```php
/*
 * Hide WPP's widget if there's nothing to show
 */
function my_custom_no_posts_found( $no_data_html ){ 
    $output = '<style type="text/css">.popular-posts { display:none; }</style>';
    return $output;
}
add_filter( 'wpp_no_data', 'my_custom_no_posts_found', 10, 1 );
```

A little explanation:

If your theme registers its sidebars properly, WPP will add the `.popular-posts` CSS class to the container that holds the widget (see the `%2$s` placeholder in [before_widget](https://codex.wordpress.org/Function_Reference/register_sidebar)?).

You can take advantage of that to hide the entire container from view *only if* WPP has nothing to show with this little hack.

Neat, huh?

**Comment by PromInc** [comment]
Brilliant!  It's implemented and working as you suggested already.  Thanks!

**Comment by 70599** [comment]
When does this feature can be released offically?
Thanks.

**Comment by cabrerahector** [comment]
It'll probably be included with WPP 3.4. There's no ETA, though.

**Comment by PromInc** [comment]
I'm happy to hear this feature is still on your radar.  I'd love to see this officially implemented!

**Comment by PromInc** [comment]
Did this enhancement make it into the plugin?

Thank you.
