### ISSUE TITLE
base api

### ISSUE THREAD

**Issue by hasangilak** [cabrerahector/wordpress-popular-posts#88]
all I want from your plugin was list of post ids. I didnt found any lower api that doesnt output any html. so i just took it out from your code
tnx for your affert 
https://gist.github.com/hasangilak/828f17c7dc2ecfd6302c

**Comment by cabrerahector** [comment]
Hi @hasangilak!

Indeed, there's no public API for that. However, there are a couple of [workarounds](https://github.com/cabrerahector/wordpress-popular-posts/issues/80) out there already :)
