### ISSUE TITLE
wpp_gets_views Location

### ISSUE THREAD

**Issue by X-Raym** [cabrerahector/wordpress-popular-posts#92]
Hi,

I don't see where wpp_gets_views() is declared in the php files.

Did I miss something ?

**Comment by cabrerahector** [comment]
Hi there!

It's [right here](https://github.com/cabrerahector/wordpress-popular-posts/blob/3.3.2/wordpress-popular-posts.php#L3240 "wpp_get_views() function") (as of ver. 3.3.2).

**Comment by X-Raym** [comment]
@cabrerahector 
Oh, shame on me, my Search was active on ALL files except the main opened document. ^^
Thanks !
