### ISSUE TITLE
Add ability to choose image from first attached image

### ISSUE THREAD

**Issue by serglopatin** [cabrerahector/wordpress-popular-posts#93]
Currently I need this feature:
Pick image from: "First image from attachements"

For example I have posts, where there is no featured image, there is no image in post, but there is image attachment and I want to display it in Popular Posts.

Let me know if this is ok and I can send pull request.

Thanks

**Comment by cabrerahector** [comment]
Hi @serglopatin!

Sounds good, please send the PR so I can review your changes :)

**Comment by serglopatin** [comment]
Ok great!  Will send it over this weekend.
