### ISSUE TITLE
Add Total Views in Admin Columns

### ISSUE THREAD

**Issue by X-Raym** [cabrerahector/wordpress-popular-posts#94]
Hi !

I just elaborate a code snippet that add a Total Views column in all admin edit screen pages (posts, custom posts types etc...).

https://gist.github.com/X-Raym/896dfa97101fc17c1250

[Screenshot](https://monosnap.com/file/LfLNYYqeGl9iZULDkaiNlcFLO0PPic.png)

It would be nice to integrate it in a next release :)

Cheers !

**Comment by jjmpsp** [comment]
+1 Thanks for this :+1:

**Comment by cabrerahector** [comment]
Hey guys!

While I appreciate the contribution, I'm not too sure about adding this feature to the plugin since this is something that can be done via functions.php as well. I'd prefer keeping the plugin as lean as possible.
